import React,{useState} from 'react';
import {Image,Modal,Pressable,View} from 'react-native';
import {ActivityArt} from './ActivityArt';
import type {ActivityKey} from './model';
import {Avatar,Button,Card,Chip,Icon,Input,Row,Screen,Txt,useTheme} from './ui';

export const samplePeople=[
 {name:'Amara D.',bio:'Reformer mornings, long walks, and coffee after class. Working on showing up three times a week.',workout:'Reformer Pilates',count:4},
 {name:'Jordan M.',bio:'A little climbing, a little lifting. Always happy to meet someone for a relaxed bouldering session.',workout:'Climbing',count:3},
 {name:'Lena R.',bio:'Barre regular. Big fan of a good playlist and a slow Sunday morning.',workout:'Barre',count:3},
 {name:'Omar K.',bio:'Weights after work. Training to feel stronger, one good session at a time.',workout:'Weights',count:2},
 {name:'Jess M.',bio:'Yoga when I need to slow down. Boxing when I need to let it out.',workout:'Yoga',count:2},
 {name:'Mateo S.',bio:'Trying new classes and making workouts a regular part of my week.',workout:'Cycling',count:1},
];
export function SampleAvatar({index,size=42}:{index:number;size?:number}){
 return <View accessibilityLabel={`Fictional profile photo of ${samplePeople[index]?.name}`} style={{width:size,height:size,borderRadius:size/2,overflow:'hidden',backgroundColor:'#dedad3'}}><Image source={require('../../assets/community-portraits.png')} style={{position:'absolute',width:size*2,height:size*3,left:-(index%2)*size,top:-Math.floor(index/2)*size}}/></View>;
}
export function SampleProfile({index,onClose}:{index:number|null;onClose:()=>void}){
 const t=useTheme();const [added,setAdded]=useState<number[]>([]);if(index===null)return null;const p=samplePeople[index]!;
 return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={{flex:1,backgroundColor:'#00000044',justifyContent:'flex-end'}}><View style={{maxHeight:'85%',backgroundColor:t.paper,borderTopLeftRadius:30,borderTopRightRadius:30,paddingTop:8}}><Screen style={{gap:20,paddingBottom:35}}><Row><Chip title="Sample profile"/><View style={{flex:1}}/><Pressable accessibilityLabel="Close sample profile" onPress={onClose} style={{padding:12}}><Icon name="x"/></Pressable></Row><View style={{alignItems:'center',gap:12}}><SampleAvatar index={index} size={92}/><Txt serif size={34}>{p.name}</Txt><Txt muted>{p.workout} · {p.count} {p.count===1?"session":"sessions"} this week</Txt></View><Card style={{gap:12}}><Txt bold>About me</Txt><Txt style={{lineHeight:24}}>{p.bio}</Txt></Card><Card style={{gap:8}}><Row><Icon name="link"/><Txt bold>Instagram</Txt></Row><Txt muted size={13}>A member’s Instagram link could appear here.</Txt><Txt muted size={11}>Placeholder · no real account linked</Txt></Card><Button title={added.includes(index)?'Added in this preview':'Add friend · preview'} onPress={()=>setAdded(old=>old.includes(index)?old.filter(i=>i!==index):[...old,index])}/><Txt muted size={12} style={{textAlign:'center'}}>This person and photo are fictional. Preview actions stay on this screen and send no requests.</Txt></Screen></View></View></Modal>;
}
export function SampleStudioBoard({name='You',count=0,showYou=true}:{name?:string;count?:number;showYou?:boolean}){
 const t=useTheme();const [profile,setProfile]=useState<number|null>(null);const rank=1+samplePeople.filter(p=>p.count>count).length;
 return <View style={{gap:12}}>{showYou&&<Card style={{backgroundColor:t.tint,gap:10}}><Row><Avatar name={name}/><View style={{flex:1}}><Txt bold>{name}</Txt><Txt muted size={12}>Your place on this example board</Txt></View><Txt numeric size={32}>#{rank}</Txt></Row><Txt muted size={11}>Your real weekly count: {count}. Other people below are examples.</Txt></Card>}{samplePeople.map((p,i)=><Pressable key={p.name} accessibilityRole="button" accessibilityLabel={`View sample profile ${p.name}`} onPress={()=>setProfile(i)}><Card style={{padding:14}}><Row style={{gap:13}}><Txt muted size={13} style={{width:18}}>{i+1+(showYou&&i+1>=rank?1:0)}</Txt><SampleAvatar index={i}/><View style={{flex:1,gap:3}}><Txt bold size={15}>{p.name}</Txt><Txt muted size={11}>{p.workout}</Txt></View><Txt bold size={13}>{p.count} {p.count===1?"session":"sessions"}</Txt><Icon name="chevron" size={12}/></Row></Card></Pressable>)}<SampleProfile index={profile} onClose={()=>setProfile(null)}/></View>;
}
function SampleWorkoutPhoto({index,width}:{index:number;width:number}){
 return <View style={{width,height:width,overflow:'hidden'}}><Image source={require('../../assets/community-workouts.png')} style={{width:width*2,height:width,position:'absolute',left:-index*width}}/><View style={{position:'absolute',left:18,bottom:18,maxWidth:width*.73,padding:index?0:15,borderRadius:16,backgroundColor:index?'transparent':'#413c325c',gap:5}}><Txt serif size={index?30:24} style={{color:'#fff',textShadowColor:'#00000077',textShadowRadius:6,textShadowOffset:{width:0,height:1}}}>{index?'One more route.':'Reformer Pilates'}</Txt><Txt bold size={12} style={{color:'#fff'}}>{index?'Climbing · 64 min':'48 min · 3 this week'}</Txt><Txt size={9} bold style={{color:'#fff',letterSpacing:1.4}}>CLASSSTREAK</Txt></View></View>;
}
const samplePosts:{person:number;key:ActivityKey;label:string;caption:string;duration:number;count:number;goal:number;time:string;photo?:number}[]=[
 {person:0,key:'reformer',label:'Reformer Pilates',caption:'Finished a full class before the day got busy.',duration:48,count:3,goal:4,time:'This morning',photo:0},
 {person:1,key:'custom:Climbing',label:'Climbing',caption:'Stayed for one more route. Glad I did.',duration:64,count:3,goal:3,time:'2 hours ago',photo:1},
 {person:2,key:'barre',label:'Barre',caption:'Legs shaking. Playlist perfect. See you next week.',duration:45,count:2,goal:3,time:'3 hours ago'},
 {person:3,key:'gym',label:'Weights · Pull day',caption:'One extra rep on the last set. Taking that win.',duration:57,count:2,goal:4,time:'4 hours ago'},
 {person:4,key:'yoga',label:'Yoga',caption:'Needed this after a long day at my desk.',duration:50,count:2,goal:3,time:'Yesterday'},
 {person:5,key:'cycling',label:'Cycling',caption:'The hill was rude. The ride home was worth it.',duration:42,count:1,goal:3,time:'Yesterday'},
 {person:4,key:'boxing',label:'Boxing',caption:'Got through every round. That’s enough for today.',duration:55,count:1,goal:3,time:'Yesterday'},
 {person:0,key:'mat',label:'Mat Pilates',caption:'A slower class, exactly what I needed.',duration:35,count:2,goal:4,time:'Yesterday'},
 {person:3,key:'gym',label:'Weights · Legs',caption:'Made it in after work. Future me is grateful.',duration:61,count:1,goal:4,time:'2 days ago'},
 {person:5,key:'hiit',label:'HIIT',caption:'Short session. Absolutely counted.',duration:28,count:1,goal:3,time:'2 days ago'},
 {person:2,key:'yoga',label:'Yoga',caption:'Sunday stretch with a friend. Keeping this tradition.',duration:40,count:1,goal:3,time:'3 days ago'},
 {person:1,key:'custom:Climbing',label:'Climbing',caption:'Finally got the route I’ve been working on.',duration:72,count:2,goal:3,time:'3 days ago'},
];
function SamplePost({index,onProfile}:{index:number;onProfile:(n:number)=>void}){
 const t=useTheme();const [liked,setLiked]=useState(false);const [comments,setComments]=useState<string[]>([]);const [writing,setWriting]=useState(false);const [text,setText]=useState('');const [width,setWidth]=useState(300);const post=samplePosts[index]!;const p=samplePeople[post.person]!;
 return <Card style={{padding:0,gap:0,overflow:'hidden'}}><Pressable accessibilityRole="button" onPress={()=>onProfile(post.person)} accessibilityLabel={`Open ${p.name} sample profile`} style={{padding:15}}><Row><SampleAvatar index={post.person}/><View style={{flex:1,gap:3}}><Txt bold>{p.name}</Txt><Txt muted size={11}>{post.label} · {post.time}</Txt></View><View style={{paddingVertical:4,paddingHorizontal:8,borderRadius:8,backgroundColor:t.tint}}><Txt bold size={9} style={{color:t.accent}}>EXAMPLE</Txt></View></Row></Pressable>
 {post.photo!==undefined?<View onLayout={e=>setWidth(e.nativeEvent.layout.width)} style={{width:'100%'}}><SampleWorkoutPhoto index={post.photo} width={width}/></View>:<View style={{marginHorizontal:15,borderRadius:22,padding:19,backgroundColor:index%3===0?'#E5ECDD':index%3===1?'#F1DDD3':t.tint,gap:16}}><Row style={{gap:13}}><ActivityArt activityKey={post.key} size={80}/><View style={{flex:1,gap:5}}><Txt serif size={25}>{post.label}</Txt><Txt bold size={11} style={{color:t.accent}}>SHOWED UP. LOGGED IT.</Txt></View></Row><Row style={{justifyContent:'space-between'}}><Txt bold size={14}>{post.duration} min</Txt><Txt size={12}>{post.count}/{post.goal} goal this week</Txt></Row><View style={{height:4,borderRadius:2,backgroundColor:'#ffffff99'}}><View style={{height:4,borderRadius:2,width:`${Math.min(100,post.count/post.goal*100)}%`,backgroundColor:t.accent}}/></View></View>}
 <View style={{padding:16,gap:12}}><Txt size={14}>{post.caption}</Txt><Row style={{gap:22}}><Pressable accessibilityRole="button" accessibilityState={{selected:liked}} accessibilityLabel="Like sample workout" onPress={()=>setLiked(!liked)} style={{minHeight:44,justifyContent:'center'}}><Row style={{gap:7}}><Icon name="heart" size={20} color={liked?t.accent:t.ink}/><Txt bold size={13} style={{color:liked?t.accent:t.ink}}>{12+index*3+Number(liked)}</Txt></Row></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Comment on sample workout" onPress={()=>setWriting(!writing)} style={{minHeight:44,justifyContent:'center'}}><Row style={{gap:7}}><Icon name="comment" size={18}/><Txt size={12}>{1+comments.length} {comments.length?'comments':'comment'}</Txt></Row></Pressable></Row><View style={{height:1,backgroundColor:t.line}}/><Txt size={12}><Txt size={12} bold>{samplePeople[(post.person+2)%6]!.name.split(' ')[0]}</Txt>  {['Love this!','See you next time?','You showed up!'][index%3]}</Txt>{comments.map((c,i)=><Txt key={i} size={12}><Txt bold size={12}>You · preview</Txt>  {c}</Txt>)}{writing&&<><Input label="Try a comment (preview only)" value={text} onChange={value=>setText(value.slice(0,240))}/><Button small title="Add preview comment" disabled={!text.trim()} onPress={()=>{setComments([...comments,text.trim()]);setText('');setWriting(false);}}/></>}</View></Card>;
}
export function CommunityPreview(){
 const t=useTheme();const [profile,setProfile]=useState<number|null>(null);
 return <View style={{gap:17,marginTop:8}}><Row style={{gap:8}}><View style={{width:27,height:2,backgroundColor:t.accent}}/><Txt bold size={10} style={{color:t.accent,letterSpacing:1.5}}>THE WORKOUT CROWD</Txt></Row><Txt serif size={30}>Good workouts.{'\n'}Better company.</Txt><Txt muted size={12}>Example posts from fictional people. Try a like or comment here; it stays in this preview.</Txt>{samplePosts.map((_,i)=><SamplePost key={i} index={i} onProfile={setProfile}/>)}<View style={{alignItems:'center',gap:10,paddingVertical:24}}><Icon name="flame" color={t.accent} size={25}/><Txt serif size={22} style={{textAlign:'center'}}>Here’s to the next workout.</Txt><Txt muted size={11}>Show up for yourself. Cheer on your people.</Txt></View><SampleProfile index={profile} onClose={()=>setProfile(null)}/></View>;
}
