import React,{useState} from 'react';
import {Image,Modal,Pressable,View} from 'react-native';
import {Avatar,Button,Card,Chip,Icon,Input,Row,Screen,Txt,useTheme} from './ui';

export const samplePeople=[
 {name:'Amara D.',bio:'Reformer mornings, long walks, and coffee after class. Working on showing up three times a week.',workout:'Reformer Pilates',count:4},
 {name:'Jordan M.',bio:'A little climbing, a little lifting. Always happy to meet someone for a relaxed bouldering session.',workout:'Climbing',count:3},
 {name:'Lena R.',bio:'Barre regular. Big fan of a good playlist and a slow Sunday morning.',workout:'Barre',count:3},
 {name:'Omar K.',bio:'Weights after work. Training to feel stronger, one good session at a time.',workout:'Weights',count:2},
 {name:'Jess M.',bio:'Yoga when I need to slow down. Boxing when I need to let it out.',workout:'Yoga',count:2},
 {name:'Mateo S.',bio:'Trying new classes and making movement a regular part of my week.',workout:'Cycling',count:1},
];
export function SampleAvatar({index,size=42}:{index:number;size?:number}){
 return <View accessibilityLabel={`Fictional profile photo of ${samplePeople[index]?.name}`} style={{width:size,height:size,borderRadius:size/2,overflow:'hidden',backgroundColor:'#dedad3'}}><Image source={require('../../assets/community-portraits.png')} style={{position:'absolute',width:size*2,height:size*3,left:-(index%2)*size,top:-Math.floor(index/2)*size}}/></View>;
}
export function SampleProfile({index,onClose}:{index:number|null;onClose:()=>void}){
 const t=useTheme();const [added,setAdded]=useState<number[]>([]);if(index===null)return null;const p=samplePeople[index]!;
 return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={{flex:1,backgroundColor:'#00000044',justifyContent:'flex-end'}}><View style={{maxHeight:'85%',backgroundColor:t.paper,borderTopLeftRadius:30,borderTopRightRadius:30,paddingTop:8}}><Screen style={{gap:20,paddingBottom:35}}><Row><Chip title="Sample profile"/><View style={{flex:1}}/><Pressable accessibilityLabel="Close sample profile" onPress={onClose} style={{padding:12}}><Icon name="x"/></Pressable></Row><View style={{alignItems:'center',gap:12}}><SampleAvatar index={index} size={92}/><Txt serif size={34}>{p.name}</Txt><Txt muted>{p.workout} · {p.count} {p.count===1?"session":"sessions"} this week</Txt></View><Card style={{gap:12}}><Txt bold>About me</Txt><Txt style={{lineHeight:24}}>{p.bio}</Txt></Card><Card style={{gap:8}}><Row><Icon name="link"/><Txt bold>Instagram</Txt></Row><Txt muted size={13}>A member’s Instagram link could appear here.</Txt><Txt muted size={11}>Placeholder · no real account linked</Txt></Card><Button title={added.includes(index)?'Added in this preview':'Add friend · preview'} onPress={()=>setAdded(old=>old.includes(index)?old.filter(i=>i!==index):[...old,index])}/><Txt muted size={12} style={{textAlign:'center'}}>This person and photo are fictional. Preview actions stay on this screen and send no requests.</Txt></Screen></View></View></Modal>;
}
export function SampleStudioBoard({name='You',count=0}:{name?:string;count?:number}){
 const t=useTheme();const [profile,setProfile]=useState<number|null>(null);const rank=1+samplePeople.filter(p=>p.count>count).length;
 return <View style={{gap:12}}><Card style={{backgroundColor:t.tint,gap:10}}><Row><Avatar name={name}/><View style={{flex:1}}><Txt bold>{name}</Txt><Txt muted size={12}>Your place on this example board</Txt></View><Txt serif size={32}>#{rank}</Txt></Row><Txt muted size={11}>Your real weekly count: {count}. Other people below are examples.</Txt></Card>{samplePeople.map((p,i)=><Pressable key={p.name} accessibilityRole="button" accessibilityLabel={`View sample profile ${p.name}`} onPress={()=>setProfile(i)}><Card style={{padding:14}}><Row style={{gap:13}}><Txt muted size={13} style={{width:18}}>{i+1+(i+1>=rank?1:0)}</Txt><SampleAvatar index={i}/><View style={{flex:1,gap:3}}><Txt bold size={15}>{p.name}</Txt><Txt muted size={11}>{p.workout}</Txt></View><Txt bold size={13}>{p.count} {p.count===1?"session":"sessions"}</Txt><Icon name="chevron" size={12}/></Row></Card></Pressable>)}<SampleProfile index={profile} onClose={()=>setProfile(null)}/></View>;
}
function SampleWorkoutPhoto({index,width}:{index:number;width:number}){
 return <View style={{width,height:width,overflow:'hidden',borderRadius:20}}><Image source={require('../../assets/community-workouts.png')} style={{width:width*2,height:width,position:'absolute',left:-index*width}}/><View style={{position:'absolute',left:18,bottom:18,maxWidth:width*.73,padding:index?0:15,borderRadius:16,backgroundColor:index?'transparent':'#1c211d70',gap:5}}><Txt serif size={index?30:24} style={{color:'#fff',textShadowColor:'#00000077',textShadowRadius:6,textShadowOffset:{width:0,height:1}}}>{index?'A little higher.':'Reformer Pilates'}</Txt><Txt bold size={12} style={{color:'#fff'}}> {index?'Climbing · 64 min':'48 min · 3 this week'}</Txt><Txt size={9} bold style={{color:'#fff',letterSpacing:1.4}}>CLASSSTREAK</Txt></View></View>;
}
function SamplePost({index,onProfile}:{index:number;onProfile:(n:number)=>void}){
 const t=useTheme();const [liked,setLiked]=useState(false);const [comments,setComments]=useState<string[]>([]);const [writing,setWriting]=useState(false);const [text,setText]=useState('');const [width,setWidth]=useState(300);const p=samplePeople[index]!;
 return <Card style={{padding:14,gap:14}}><Pressable onPress={()=>onProfile(index)} accessibilityLabel={`Open ${p.name} sample profile`}><Row><SampleAvatar index={index}/><View style={{flex:1,gap:3}}><Txt bold>{p.name}</Txt><Txt muted size={11}>{p.workout} · {index?'2 hours ago':'This morning'} · Sample</Txt></View><Icon name="chevron" size={15}/></Row></Pressable><View onLayout={e=>setWidth(e.nativeEvent.layout.width)} style={{width:'100%'}}><SampleWorkoutPhoto index={index} width={width}/></View><Txt size={14}>{index?'Stayed for one more route. Glad I did.':'Made time for myself before the day got busy.'}</Txt><Row style={{gap:20}}><Pressable accessibilityRole="button" accessibilityState={{selected:liked}} accessibilityLabel="Like sample workout" onPress={()=>setLiked(!liked)} style={{minHeight:44,justifyContent:'center'}}><Txt bold size={13} style={{color:liked?t.accent:t.muted}}>{liked?'♥':'♡'}  {12+index*3+Number(liked)}</Txt></Pressable><Pressable onPress={()=>setWriting(!writing)} style={{minHeight:44,justifyContent:'center'}}><Txt size={13}>↳  {1+comments.length} {comments.length?"comments":"comment"}</Txt></Pressable></Row><Txt size={12}><Txt size={12} bold>{index?'Lena':'Jess'}</Txt>  {index?'That route looks so good!':'Best start to the morning.'}</Txt>{comments.map((c,i)=><Txt key={i} size={12}><Txt bold size={12}>You · preview</Txt>  {c}</Txt>)}{writing&&<><Input label="Try a comment (preview only)" value={text} onChange={value=>setText(value.slice(0,240))}/><Button small title="Add preview comment" disabled={!text.trim()} onPress={()=>{setComments([...comments,text.trim()]);setText('');setWriting(false);}}/></>}</Card>;
}
export function CommunityPreview(){
 const [open,setOpen]=useState(false);const [profile,setProfile]=useState<number|null>(null);
 return <View style={{gap:14,marginTop:14}}><Txt serif size={29}>A little shared momentum.</Txt><Txt muted size={13}>A look at how your community could feel.</Txt><Button secondary title={open?'Hide sample feed':'Explore the sample feed'} onPress={()=>setOpen(!open)}/>{open&&<><Txt muted size={11}>EXAMPLE COMMUNITY · Fictional people, photos and workouts. Likes and comments are preview-only.</Txt><SamplePost index={0} onProfile={setProfile}/><SamplePost index={1} onProfile={setProfile}/><Txt serif size={22} style={{textAlign:'center',padding:20}}>Good days start with showing up.</Txt></>}<SampleProfile index={profile} onClose={()=>setProfile(null)}/></View>;
}
