import {BouncePressable,useReducedMotion} from "./motion";
import React,{useState} from "react";
import {Pressable,ScrollView,View,TextInput,LayoutAnimation} from "react-native";
import QRCode from "react-native-qrcode-svg";
import {type Snapshot,type Friend,type FeedItem,weekDays,fullDays,activity,timeLabel,type WeekDetail} from "./model";
import {progress,dayKey} from "./engine";
import {Avatar,Button,Card,Divider,Empty,Icon,Input,Row,Txt,useTheme} from "./ui";
import type {Action} from "./SessionScreens";
import {PrivatePhoto} from "./PrivatePhoto";
export const inviteLink=(code:string)=>(process.env.EXPO_PUBLIC_INVITE_BASE_URL??"https://classstreak.app")+"/j/"+code;
export function Friends({snapshot:s,action,now}:{snapshot:Snapshot;action:Action;now:Date}){
 const t=useTheme();const [tab,setTab]=useState("league");const [focus,setFocus]=useState<string|null>(null);const reduced=useReducedMotion();const own=progress(s.sessions,s.weeks,s.goals,s.profile.tz,now);
 const me:Friend={id:s.profile.id,first_name:"You",status:"accepted",requested_by:s.profile.id,weekly_count:own.count,weekly_goal:own.goal,streak:own.streak,days:[...new Set(s.sessions.filter(x=>!x.removed_at&&x.counted&&x.week_key===own.week).map(x=>(new Date(x.day_key+"T12:00:00Z").getUTCDay()+6)%7))],usual_days:s.usual_days.map(d=>d.weekday),is_demo:false};
 me.week_details=s.sessions.filter(x=>!x.removed_at&&x.week_key===own.week).map(x=>({day:(new Date(x.day_key+"T12:00:00Z").getUTCDay()+6)%7,activity_key:x.activity_key,workout_label:x.workout_label,duration_sec:x.duration_sec,time_of_day:(()=>{const h=Number(new Intl.DateTimeFormat("en-US",{hour:"numeric",hourCycle:"h23",timeZone:s.profile.tz}).format(new Date(x.started_at)));return h<11?"morning":h<16?"midday":"evening";})()}));
 const palette=[t.accent,t.ink,t.muted];const keys=[...new Set([...(me.week_details??[]),...s.friends.flatMap(f=>f.week_details??[])].map(x=>x.activity_key))];const color=(key:string)=>palette[Math.max(0,keys.indexOf(key as WeekDetail['activity_key']))%palette.length];
 const accepted=s.friends.filter(f=>f.status==="accepted");const rows=[me,...accepted].sort((a,b)=>b.weekly_count-a.weekly_count||(b.weekly_count/Math.max(1,b.weekly_goal))-(a.weekly_count/Math.max(1,a.weekly_goal))||a.first_name.localeCompare(b.first_name));
 const leaders=rows.filter(f=>f.weekly_count===rows[0]!.weekly_count);const nudge=accepted.find(f=>f.nudge_available);const gap=rows[0]!.weekly_count-me.weekly_count;
 const today=(new Date(dayKey(now,s.profile.tz)+"T12:00:00Z").getUTCDay()+6)%7;
 return <View style={{gap:12}}><Row style={{borderRadius:99,backgroundColor:t.line,padding:4,gap:0}}>{["league","activity"].map(v=><Pressable key={v} accessibilityRole="tab" accessibilityState={{selected:tab===v}} onPress={()=>setTab(v)} style={{flex:1,padding:10,borderRadius:99,backgroundColor:tab===v?t.card:"transparent",alignItems:"center"}}><Txt bold={tab===v} size={12}>{v==="league"?"League":"Activity"}</Txt></Pressable>)}</Row>
 {s.friends.some(f=>f.status==="pending"&&f.requested_by!==s.profile.id)&&<Button secondary title="Friend requests" onPress={()=>action("navigate",{pane:"add-friends"})}/>}
 {!accepted.length&&<Empty title="Your people, your week." body="Add a friend to see your sessions side by side." action="Add friends" onPress={()=>action("navigate",{pane:"add-friends"})}/>}
 {tab==="league"?<><Card style={{gap:18,padding:13}}><Row><Txt muted size={10} bold style={{flex:1,letterSpacing:.7}}>SESSIONS THIS WEEK</Txt><Txt muted size={10}>{new Date(own.week+"T12:00:00Z").toLocaleDateString("en-US",{month:"short",day:"numeric"})} – {new Date(Date.parse(own.week+"T12:00:00Z")+6*86400000).getUTCDate()}</Txt></Row><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{flexGrow:1,justifyContent:"space-around",gap:12}}>{rows.map(f=><View key={f.id} style={{alignItems:"center",gap:5,minWidth:43}}><View style={{height:12}}>{leaders.includes(f)&&f.weekly_count>0&&<Icon name="crown" color={t.accent} size={14}/>}</View><Avatar name={f.id===me.id?s.profile.first_name:f.first_name} own={f.id===me.id}/><Txt serif size={30}>{f.weekly_count}</Txt><Txt size={11}>{f.first_name}</Txt>{f.is_demo&&<Txt size={8} muted>demo</Txt>}</View>)}</ScrollView><View style={{gap:7}}><View style={{height:8,borderRadius:8,backgroundColor:t.line}}><View style={{height:8,borderRadius:8,backgroundColor:t.accent,width:`${Math.min(100,me.weekly_count/Math.max(1,rows[0]!.weekly_count)*100)}%`}}/></View><Txt bold size={12} style={{textAlign:"center"}}>{gap>0?`${leaders.map(f=>f.first_name).join(" & ")} lead · you’re ${gap} behind`:accepted.length?"You are in the lead. Keep going.":"Your first week starts here."}</Txt></View></Card>
 {nudge&&<Nudge friend={nudge} action={action}/>}
 <Row><Txt serif size={23} style={{flex:1}}>When they went</Txt><Txt muted size={10}>everyone’s goal is different</Txt></Row>
 {rows.map(f=><Pressable key={f.id} accessibilityRole="button" accessibilityState={{expanded:focus===f.id}} onPress={()=>{if(!reduced)LayoutAnimation.configureNext({...LayoutAnimation.Presets.easeInEaseOut,duration:200});setFocus(focus===f.id?null:f.id);}}><Card style={{padding:10,borderRadius:17,backgroundColor:f.id===me.id?t.tint:t.card,borderColor:f.id===me.id?t.ink:t.line}}><Row style={{gap:7}}><Avatar name={f.id===me.id?s.profile.first_name:f.first_name} size={28}/><Txt bold size={10} style={{width:49}}>{f.first_name}</Txt><Row style={{gap:4,flex:1,justifyContent:"center"}}>{weekDays.map((d,i)=><View key={i} style={{alignItems:"center",gap:3}}><View accessibilityLabel={`${fullDays[i]} ${f.days.includes(i)?"session logged":"no session"}`} style={{width:15,height:15,borderRadius:10,backgroundColor:f.days.includes(i)?color(f.week_details?.find(x=>x.day===i)?.activity_key??"reformer"):t.line,borderWidth:f.nudge_available&&i===today?1:0,borderStyle:"dashed",borderColor:t.muted}}/><Txt size={7} muted>{d}</Txt></View>)}</Row><Txt bold size={10}>{f.weekly_count}/{f.weekly_goal}</Txt></Row>{focus===f.id&&<View style={{gap:12,marginTop:18}}>{f.week_details?.length?f.week_details.map((d,i)=><Row key={i}><Icon name={activity(d.activity_key).icon} color={color(d.activity_key)}/><View style={{flex:1}}><Txt bold size={13}>{d.workout_label}</Txt><Txt muted size={12}>{fullDays[d.day]} · {timeLabel[d.time_of_day]} · {Math.round(d.duration_sec/60)} min</Txt></View></Row>):<Txt muted size={13}>A fresh week. Your next session goes here.</Txt>}</View>}</Card></Pressable>)}<Row style={{flexWrap:"wrap"}}>{keys.map(key=><Row key={key} style={{gap:5}}><View style={{width:9,height:9,borderRadius:5,backgroundColor:color(key)}}/><Icon name={activity(key).icon} size={13}/><Txt muted size={10}>{activity(key).short}</Txt></Row>)}</Row>
 </>:<>{!s.feed.length&&<Empty title="It starts with a session." body="Your friends’ sessions, photos and reactions will appear here."/>}{s.feed.map((item,index)=><React.Fragment key={item.id}><ActivityCard item={item} me={s.profile.id} action={action}/>{index===0&&nudge&&<Nudge friend={nudge} action={action}/>}{rows.filter(f=>f.id===item.user_id&&f.weekly_goal>0&&f.weekly_count>=f.weekly_goal&&s.feed.find(x=>x.user_id===f.id)?.id===item.id).map(f=><Card key={"goal:"+f.id}><Row><Avatar name={f.first_name}/><Txt size={13} style={{flex:1}}><Txt bold size={13}>{f.first_name}</Txt> hit {f.id===me.id?"your":"their"} goal · {f.weekly_count} of {f.weekly_goal}</Txt><Icon name="check" color={t.accent}/></Row></Card>)}{s.achievements?.filter(m=>m.id===item.id).map(m=><MilestoneActivity key={m.id} item={m} me={me.id}/>)}</React.Fragment>)}{s.achievements?.filter(m=>!s.feed.some(f=>f.id===m.id)).map(m=><MilestoneActivity key={m.id} item={m} me={me.id}/>)}</>}
 </View>;
}
function MilestoneActivity({item:m,me}:{item:NonNullable<Snapshot['achievements']>[number];me:string}){const t=useTheme();return <Card><Row><Avatar name={m.first_name}/><Txt size={13} style={{flex:1}}><Txt bold size={13}>{m.user_id===me?"You":m.first_name}</Txt> hit {m.count} {m.count===1?"class":"classes"}{m.source==="seed"?" · demo":m.source==="simulated"?" · simulated":""}</Txt><Icon name="trophy" color={t.accent}/></Row></Card>;}
function Nudge({friend:f,action}:{friend:Friend;action:Action}){return <Card style={{padding:12,borderRadius:20}}><Row><Avatar name={f.first_name}/><View style={{flex:1}}><Txt size={12}><Txt bold size={12}>{f.first_name}</Txt> usually goes {f.usual_days.map(d=>fullDays[d]+"s").join(" / ")}</Txt><Txt muted size={10}>Nothing logged yet{f.is_demo?" · demo":""}</Txt></View><Button small title="Nudge" onPress={()=>action("social",{action:"nudge",payload:{id:f.id}})}/></Row></Card>;}
function ActivityCard({item,me,action}:{item:FeedItem;me:string;action:Action}){
 const t=useTheme();const [expanded,setExpanded]=useState(false);const [body,setBody]=useState("");const [emojiOpen,setEmojiOpen]=useState(false);const [emoji,setEmoji]=useState("");const comments=expanded?item.comments:item.comments.slice(-1);
 return <Card style={{gap:9}}><Row><Avatar name={item.first_name}/><View style={{flex:1}}><Txt size={13}><Txt size={13} bold>{item.user_id===me?"You":item.first_name}</Txt> went to {item.workout_label}</Txt><Txt muted size={10}>{item.place_name?item.place_name+" · ":""}{item.relative_time}{item.source==="seed"?" · demo":item.source==="simulated"?" · simulated":item.source==="manual"?" · manual, unverified":""}</Txt></View></Row>
 {item.photo_url&&<PrivatePhoto key={item.photo_url} path={item.photo_url}/>}{!!item.note&&<Txt size={13}>{item.note}</Txt>}
 <Row style={{gap:6,flexWrap:"wrap"}}>{[...new Set(["🔥","👏","💀","🫡",...item.reactions.map(r=>r.emoji)])].map(emoji=>{const r=item.reactions.find(r=>r.emoji===emoji);return <BouncePressable key={emoji} accessibilityRole="button" accessibilityLabel={`React ${emoji}, ${r?.count??0} reactions`} accessibilityState={{selected:r?.mine??false}} onPress={()=>action("social",{action:"reaction",payload:{session_id:item.id,emoji}})} style={{minHeight:44,minWidth:52,borderWidth:1,borderColor:r?.mine?t.accent:t.line,borderRadius:12,backgroundColor:r?.mine?t.tint:t.paper,padding:8,justifyContent:"center"}}><Txt size={12}>{emoji}  {r?.count??""}</Txt></BouncePressable>;})}<Button small secondary title="+" onPress={()=>setEmojiOpen(!emojiOpen)}/></Row>{emojiOpen&&<View style={{gap:8}}><Txt muted size={12}>Choose an emoji using the smiley key on your keyboard.</Txt><TextInput autoFocus accessibilityLabel="Custom emoji" value={emoji} onChangeText={setEmoji} maxLength={24} placeholder="Your emoji" style={{fontSize:24,padding:12,borderWidth:1,borderColor:t.line,borderRadius:14,color:t.ink}}/><Button small title="React" disabled={!emoji.trim()||!/^\p{Extended_Pictographic}[\p{Extended_Pictographic}\p{Emoji_Modifier}\uFE0F\u200D]*$/u.test(emoji)} onPress={()=>{action("social",{action:"reaction",payload:{session_id:item.id,emoji}});setEmojiOpen(false);setEmoji("");}}/></View>}
 <Row><Pressable onPress={()=>setExpanded(!expanded)} style={{flex:1,paddingVertical:5}}><Txt muted size={11}>{item.comments.length?`${item.comments.length} comments`:"No comments yet"}</Txt></Pressable><Pressable onPress={()=>setExpanded(true)} style={{paddingVertical:5}}><Txt bold size={11}>Add a comment</Txt></Pressable></Row>
 {comments.length>0&&<Divider/>}{comments.map(c=><Pressable key={c.id} onLongPress={()=>action(c.user_id===me?"delete_comment":"report_comment",{id:c.id})}><Row style={{alignItems:"flex-start",gap:6}}><Avatar name={c.first_name} size={22}/><Txt size={11} style={{flex:1}}><Txt bold size={11}>{c.first_name}</Txt> {c.body}</Txt>{expanded&&<Pressable accessibilityLabel={c.user_id===me?"Delete comment":"Report comment"} onPress={()=>action(c.user_id===me?"delete_comment":"report_comment",{id:c.id})}><Icon size={13} name={c.user_id===me?"x":"flag"}/></Pressable>}</Row></Pressable>)}
 {expanded&&<><Input label="Add a comment" value={body} onChange={v=>setBody(v.slice(0,240))}/><Button small title="Comment" disabled={!body.trim()} onPress={()=>{action("social",{action:"comment",payload:{session_id:item.id,body}});setBody("");}}/></>}
 </Card>;
}
export function AddFriends({snapshot:s,action,matches=[]}:{snapshot:Snapshot;action:Action;matches?:{id:string;first_name:string}[]}){
 const [code,setCode]=useState("");const [qr,setQr]=useState(false);
 return <View style={{gap:14}}><Txt serif size={32}>Bring your people.</Txt><Txt muted>Share a link, scan a code or find someone you know.</Txt><Button title="Share my invite" icon="share" onPress={()=>action("share_invite")}/><Row><Button secondary small title="My QR" icon="qr" onPress={()=>setQr(!qr)}/><Button secondary small title="Scan" icon="camera" onPress={()=>action("navigate",{pane:"scan"})}/><Button secondary small title="Contacts" icon="friends" onPress={()=>action("contacts")}/></Row>
 {qr&&<Card style={{alignItems:"center",gap:12}}><QRCode value={inviteLink(s.profile.invite_code)} size={190}/><Txt bold>{s.profile.invite_code}</Txt><Button secondary small title="Copy my code" onPress={()=>action("copy_invite")}/></Card>}
 <Input label="Friend code" value={code} onChange={v=>setCode(v.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,12))}/><Button secondary title="Use friend code" disabled={code.length!==12} onPress={()=>action("social",{action:"invite",payload:{code}})}/>
 {matches.map(f=><Card key={f.id}><Row><Avatar name={f.first_name}/><Txt style={{flex:1}}>{f.first_name}</Txt><Button small title="Request" onPress={()=>action("social",{action:"request",payload:{id:f.id}})}/></Row></Card>)}
 {s.friends.map(f=><Card key={f.id} style={{gap:10}}><Row><Avatar name={f.first_name}/><View style={{flex:1}}><Txt bold>{f.first_name}</Txt><Txt muted size={11}>{f.is_demo?"Demo friend":f.status==="accepted"?"Friends":f.requested_by===s.profile.id?"Request sent":"Wants to be friends"}</Txt></View></Row><Row>{f.status==="pending"&&f.requested_by!==s.profile.id&&<Button small title="Accept" onPress={()=>action("social",{action:"accept",payload:{id:f.id}})}/>}<Button small secondary title={f.status==="accepted"?"Unfriend":"Remove request"} onPress={()=>action("social",{action:"remove",payload:{id:f.id}})}/></Row></Card>)}
 </View>;
}
