import React from "react";
import { Pressable, View } from "react-native";
import { activities, activity, draftGoals, fullDays, timeLabel, weekDays, type Draft } from "./model";
import { Avatar, Button, Card, Chip, Icon, Input, Logo, Row, Screen, Txt, themes, useTheme } from "./ui";

export function Onboarding({ draft: d, change, next, requestLocation, search, account }: {
  draft: Draft; change: (value: Partial<Draft>) => void; next: () => void; requestLocation: () => void;
  search: React.ReactNode; account: React.ReactNode;
}) {
  const t = useTheme();
  const titles = ["", "What do you do?", "How many sessions a week?", "Find your studio or gym", "When do you usually go?", "One permission.\nNothing to track.", "Pick your look", "What's your name?", "How do you identify?", "Save your streak."];
  const descriptions = ["", "Pick everything that’s you.", "One answer per thing you do. This is your goal.", "Save it once. Every session after that logs itself.", "We'll remind you on those days. If you haven't gone yet, friends can cheer you on.", "", "Same app, your colors. Change them any time in You.", "Friends see your first name. Studio boards show your first name and last initial.", "Optional. Helps us show studios, events and stats that fit you. Nobody else sees it.", "Create an account so your classes, friends and look stay yours if you switch phones."];
  const steps: Record<number, string> = { 1: "1 of 7", 2: "2 of 7", 3: "3 of 7", 4: "4 of 7", 6: "5 of 7", 7: "6 of 7", 8: "7 of 7", 9: "Last step" };
  const total = Object.values(d.goals).reduce((a, b) => a + b, 0);
  const buttonTitle = d.step === 0 ? "Get started" : d.step === 6 ? "Let's go" : "Continue";
  const footer = d.step === 9 ? undefined : d.step === 3 ? <Button secondary title={d.place ? "Continue" : "Add mine later"} onPress={next} /> : d.step === 5 ? <><Button title="Turn on location" onPress={requestLocation} /><Button title="Not now" secondary onPress={next} /></> : <>
    <Button title={buttonTitle} disabled={(d.step === 1 && !d.selected.length) || (d.step === 7 && !d.first_name.trim())} onPress={next} />
    {d.step === 4 && <Button title="I don't have set days" secondary onPress={() => { change({ days: [] }); next(); }} />}
    {d.step === 8 && <Button title="Skip" secondary onPress={() => { change({ gender: null }); next(); }} />}
    {d.step === 0 && <Txt size={11} muted style={{ textAlign: "center" }}>Takes two minutes. You sign up at the end.</Txt>}
  </>;
  if (d.step === 0) return <Screen footer={footer} style={{ gap: 10 }}>
    <Logo size={25} /><Txt serif size={36}>Go to class. It counts itself.</Txt><Txt muted size={13}>Other apps make you write it down. This one notices you went.</Txt>
    <Row style={{ alignItems: "stretch" }}><Card style={{ flex: 1, padding: 12 }}><Txt bold size={11}>Other apps</Txt>{["Type your workout", "Log each set", "Remember to check in"].map(s => <Txt key={s} size={10} muted style={{ textDecorationLine: "line-through", marginTop: 6 }}>×  {s}</Txt>)}</Card><Card dark style={{ flex: 1, padding: 12 }}><Txt size={11} style={{ color: "#decbd3" }} bold>ClassStreak</Txt><Txt size={20} bold style={{ color: "#fff" }}>Just go.</Txt><Txt size={11} style={{ color: "#fff" }}>Reformer · 52 min · counted</Txt><View style={{ marginTop: 6, backgroundColor: "#ffffff22", borderRadius: 20, padding: 4 }}><Txt size={10} bold style={{ color: "#fff", textAlign: "center" }}>✓  2/3 this week</Txt></View></Card></Row>
    <Card style={{ gap: 8, padding: 14 }}><Txt bold size={14}>Three steps. Then it’s automatic.</Txt><Txt muted size={11}>Nothing to type, ever.</Txt><Row style={{ justifyContent: "space-around" }}>{[["pin", "Save your\nstudio location"], ["reformer", "Go to class"], ["flame", "It's counted"]].map(([icon, label]) => <View key={icon} style={{ alignItems: "center", gap: 6, flex: 1 }}><View style={{ padding: 14, borderRadius: 17, backgroundColor: t.paper, borderWidth: 1, borderColor: t.line }}><Icon name={icon!} size={18} /></View><Txt size={11} bold style={{ textAlign: "center" }}>{label}</Txt></View>)}</Row></Card>
    <Card style={{ gap: 7, padding: 14 }}><Txt bold size={14}>Your friends will know if you skipped.</Txt><Txt muted size={11}>A weekly league with the people who’d actually notice.</Txt>{[["Priya", 3], ["You", 2], ["Ifti", 1]].map(([name, count]) => <Row key={name} style={{ backgroundColor: name === "You" ? t.tint : t.paper, borderColor: t.line, borderWidth: 1, borderRadius: 10, padding: 7 }}><Avatar name={String(name)} size={22} /><Txt size={12} bold style={{ flex: 1 }}>{name}</Txt><Txt serif size={19}>{count}</Txt></Row>)}<Txt size={10} muted>Example league</Txt></Card>
  </Screen>;
  return <Screen footer={footer} style={{ gap: 16 }}>
    {steps[d.step] && <Row><Txt muted size={12}>{steps[d.step]}</Txt><View style={{ flex: 1 }} /><Pressable onPress={() => change({ step: Math.max(0, d.step - 1) })} accessibilityLabel="Previous step" hitSlop={14}><Icon name="back" size={16} /></Pressable></Row>}
    <View style={{ gap: 9 }}><Txt serif size={35}>{titles[d.step]}</Txt>{!!descriptions[d.step] && <Txt muted size={14}>{descriptions[d.step]}</Txt>}</View>
    {d.step === 1 && <><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>{activities.map(a => {
      const selected = d.selected.includes(a.key); return <Pressable key={a.key} accessibilityRole="checkbox" accessibilityState={{ checked: selected }} onPress={() => { const selectedKeys = selected ? d.selected.filter(k => k !== a.key) : [...d.selected, a.key]; change({ selected: selectedKeys, goals: draftGoals(selectedKeys, d.goals) }); }} style={{ width: "31.5%", minHeight: 91, padding: 13, borderRadius: 18, borderWidth: 1, borderColor: selected ? t.ink : t.line, backgroundColor: selected ? t.tint : t.card, justifyContent: "space-between" }}><Row><Icon name={a.icon} size={19} /><View style={{ flex: 1 }} />{selected && <Icon name="check" size={14} />}</Row><Txt size={13} bold>{a.label}</Txt></Pressable>;
    })}</View><Txt size={12} muted>Any gym counts for Gym. Studios count for the rest. You can add more later.</Txt></>}
    {d.step === 2 && <>{d.selected.slice(0, 2).map(key => <View key={key} style={{ gap: 8 }}><Row><Icon name={activity(key).icon} size={18} /><Txt serif size={22}>{activity(key).short}</Txt></Row>{[1, 2, 3, 4].map((v, i) => <Pressable key={v} accessibilityRole="radio" accessibilityState={{ selected: d.goals[key] === v }} onPress={() => change({ goals: { ...d.goals, [key]: v } })} style={{ minHeight: 49, borderRadius: 15, borderWidth: 1, borderColor: d.goals[key] === v ? t.ink : t.line, backgroundColor: d.goals[key] === v ? t.tint : t.card, paddingHorizontal: 16, justifyContent: "center" }}><Row><Txt serif size={25} style={{ width: 38 }}>{v === 4 ? "4+" : v}</Txt><Txt bold size={13} style={{ flex: 1 }}>{["Once a week", "Twice a week", "Three times a week", "Four or more"][i]}</Txt>{d.goals[key] === v && <Icon name="check" size={16} />}</Row></Pressable>)}</View>)}<Card><Txt muted size={12}>{d.selected.length > 2 ? `You picked ${d.selected.length} things. Set up the rest in your profile after this. ` : ""}Your weekly goal is the total: {total} sessions.</Txt></Card></>}
    {d.step === 3 && search}
    {d.step === 4 && <><Txt bold size={12}>Days</Txt><Row style={{ gap: 6, justifyContent: "space-between" }}>{weekDays.map((day, i) => <Pressable key={i} accessibilityLabel={fullDays[i]} accessibilityRole="checkbox" accessibilityState={{ checked: d.days.includes(i) }} onPress={() => change({ days: d.days.includes(i) ? d.days.filter(n => n !== i) : [...d.days, i] })} style={{ width: 40, height: 44, borderRadius: 25, alignItems: "center", justifyContent: "center", backgroundColor: d.days.includes(i) ? t.accent : t.card, borderWidth: 1, borderColor: t.line }}><Txt bold size={13} style={{ color: d.days.includes(i) ? "#fff" : t.ink }}>{day}</Txt></Pressable>)}</Row><Txt bold size={12}>Usually around</Txt><Row>{(["morning", "midday", "evening"] as const).map(time => <View key={time} style={{ flex: 1 }}><Chip title={timeLabel[time]} selected={d.time === time} onPress={() => change({ time })} /></View>)}</Row><Card style={{ gap: 10 }}><Row><Icon name="bell" size={17} /><Txt bold size={13}>What this turns on</Txt></Row><Txt muted size={12}>A reminder on your usual days. If nothing has logged yet, friends can cheer you on with a nudge in your inbox. Change or turn off any time.</Txt></Card></>}
    {d.step === 5 && <><Txt bold size={15}>Turn on location and all <Txt bold style={{ color: t.accent, textDecorationLine: "underline" }}>three</Txt> of these just happen.</Txt>{[
      ["Your workout logs itself", "Walk in, work out, walk out. It's on the board."],
      ["Post it in one tap", "A sticker with your stats, ready for your story."],
      ["Friends keep you honest", "A weekly league, and a nudge when you skip."],
    ].map(([title, body], i) => <Card key={title} style={{ backgroundColor: t.paper, gap: 10, padding: 13 }}><Row style={{ alignItems: "flex-start" }}><Avatar own name={String(i + 1)} size={26} /><View style={{ flex: 1 }}><Txt bold size={14}>{title}</Txt><Txt muted size={11}>{body}</Txt></View></Row>{i === 0 ? <Card style={{ padding: 11, borderRadius: 15 }}><Row><Icon name="reformer" /><View style={{ flex: 1 }}><Txt bold size={12}>Reformer · 52 min</Txt><Txt size={10} muted>Club Pilates Summerlin · logged</Txt></View><Icon name="check" color={t.accent} /></Row></Card> : i === 1 ? <Card dark style={{ alignSelf: "flex-start", borderRadius: 14, gap: 5 }}><Txt bold size={15} style={{ color: "#fff" }}>Reformer Pilates</Txt><Txt size={12} style={{ color: "#fff" }}>Time     This week     Streak</Txt><Txt bold size={15} style={{ color: "#fff" }}>52m        2/3          6 wk</Txt><Logo white size={15} /></Card> : ["Priya", "You", "Ifti"].map((name, j) => <Row key={name} style={{ padding: 6, backgroundColor: j === 1 ? t.tint : t.card, borderRadius: 10 }}><Avatar name={name} size={22} /><Txt bold size={12} style={{ flex: 1 }}>{name}</Txt><Txt serif size={20}>{3 - j}</Txt></Row>)}</Card>)}<Txt size={11} muted>Pick “Always” so it works with your phone in your bag. We only check your saved studios and gyms. Examples shown above.</Txt></>}
    {d.step === 6 && (["blush", "sage", "clay"] as const).map(name => <Pressable key={name} accessibilityRole="radio" accessibilityState={{ selected: d.theme === name }} onPress={() => change({ theme: name })}><Card style={{ minHeight: 148, borderColor: d.theme === name ? t.ink : t.line }}><Row style={{ flex: 1, gap: 18 }}><View style={{ width: 83, padding: 8, gap: 6, borderRadius: 16, borderWidth: 1, borderColor: t.line, backgroundColor: themes[name].paper }}><Txt serif size={11} style={{ color: themes[name].ink }}>ClassStreak.</Txt><View style={{ backgroundColor: themes[name].ink, borderRadius: 8, padding: 6 }}><Txt bold style={{ color: "#fff" }}>2/3</Txt><Row style={{ gap: 3 }}>{[0, 1, 2].map(x => <View key={x} style={{ width: 8, height: 8, borderRadius: 6, backgroundColor: x < 2 ? themes[name].accent : "#ffffff55" }} />)}</Row></View><View style={{ backgroundColor: themes[name].tint, height: 13, borderRadius: 9 }} /><View style={{ backgroundColor: themes[name].accent, height: 16, borderRadius: 9 }} /></View><View style={{ flex: 1, gap: 8 }}><Txt bold>{name[0]!.toUpperCase() + name.slice(1)}</Txt><Row style={{ gap: 5 }}>{["paper", "tint", "accent", "ink"].map(token => <View key={token} style={{ width: 21, height: 21, borderRadius: 12, backgroundColor: themes[name][token as keyof typeof t], borderWidth: 1, borderColor: t.line }} />)}</Row></View>{d.theme === name ? <View style={{ backgroundColor: t.accent, borderRadius: 20, padding: 5 }}><Icon name="check" size={16} color="#fff" /></View> : <View style={{ width: 26, height: 26, borderRadius: 20, borderColor: t.line, borderWidth: 1 }} />}</Row></Card></Pressable>)}
    {d.step === 7 && <><Input label="First name" value={d.first_name} onChange={first_name => change({ first_name })} /><Input label="Last name" value={d.last_name} onChange={last_name => change({ last_name })} /></>}
    {d.step === 8 && ["Woman", "Man", "Non-binary", "Prefer not to say"].map(gender => <Pressable key={gender} accessibilityRole="radio" accessibilityState={{ selected: d.gender === gender }} onPress={() => change({ gender })}><Card style={{ backgroundColor: d.gender === gender ? t.tint : t.card, borderColor: d.gender === gender ? t.ink : t.line, minHeight: 60, justifyContent: "center" }}><Txt bold>{gender}</Txt></Card></Pressable>)}
    {d.step === 9 && <><Card style={{ gap: 9 }}><Txt muted size={11} bold>WHAT YOU SET UP</Txt><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 6 }}>{d.selected.map(key => <Chip key={key} title={activity(key).label} icon={activity(key).icon} selected />)}<Chip title={`${total} sessions a week`} selected />{d.place && <Chip title={d.place.name} icon="pin" selected />}{d.days.length > 0 && <Chip title={d.days.map(i => fullDays[i]!.slice(0, 3)).join(" · ")} selected />}<Chip title={d.theme[0]!.toUpperCase() + d.theme.slice(1)} selected /></View></Card><View style={{ flex: 1, minHeight: 30 }} />{account}</>}
  </Screen>;
}
