import {SoftPressable as Pressable} from "./motion";
import React,{useState} from "react";
import {ActivitySchedules,CustomActivity} from "./ActivitySetup";
import { View } from "react-native";
import { activities, activity, draftGoals, fullDays, type Draft } from "./model";
import { Avatar, Button, Card, Chip, Icon, Input, Logo, Row, Screen, Txt, themes, useTheme } from "./ui";

export function Onboarding({ draft: d, change, next, requestLocation, search, account }: {
  draft: Draft; change: (value: Partial<Draft>) => void; next: () => void; requestLocation: () => void;
  search: React.ReactNode; account: React.ReactNode;
}) {
  const t = useTheme();
  const [privacy,setPrivacy]=useState(false);
  const [addingPlace,setAddingPlace]=useState(false);
  const places=d.places??(d.place?[d.place]:[]);
  const advance=()=>d.step===0?change({step:-1}):d.step===-1?change({step:1}):next();
  const titles = ["", "What do you do?", "How many sessions a week?", "Find your studio or gym", "When do you usually go?", "One permission.\nNothing to log.", "Pick your look", "What's your name?", "How do you identify?", "Save your streak."];
  const descriptions = ["", "Pick everything that’s you.", "One answer per thing you do. This is your goal.", "Save it once. Every session after that logs itself.", "We'll remind you on those days. If you haven't gone yet, friends can cheer you on.", "", "Same app, your colors. Change them any time in You.", "Friends see your first name. Studio boards show your first name and last initial.", "Optional. Helps us show studios, events and stats that fit you. Nobody else sees it.", "Create an account so your classes, friends and look stay yours if you switch phones."];
  const steps: Record<number, string> = { 1: "1 of 7", 2: "2 of 7", 3: "3 of 7", 4: "4 of 7", 6: "5 of 7", 7: "6 of 7", 8: "7 of 7", 9: "Last step" };
  const total = Object.values(d.goals).reduce((a, b) => a + b, 0);
  const buttonTitle = d.step === 0 ? "Get started" : d.step === 6 ? "Let's go" : "Continue";
  const footer = d.step === 9 ? undefined : d.step === 3 ? <Button secondary title={d.place ? "Continue" : "Add mine later"} onPress={advance} /> : d.step === 5 ? <><Button title="Turn on location" onPress={requestLocation} /><Button title="Not now" secondary onPress={advance} /></> : <>
    <Button title={buttonTitle} disabled={(d.step === 1 && !d.selected.length) || (d.step === 7 && !d.first_name.trim())} onPress={advance} />
    {d.step === 4 && <Button title="I don't have set days" secondary onPress={() => { change({ days: [],schedules:d.selected.map(activity_key=>({activity_key,days:[],time:"evening"})) }); next(); }} />}
    {d.step === 8 && <Button title="Skip" secondary onPress={() => { change({ gender: null }); next(); }} />}
    {d.step === 0 && <Txt size={11} muted style={{ textAlign: "center" }}>Takes two minutes. You sign up at the end.</Txt>}
  </>;
  if(privacy)return <Screen footer={<Button title="Back" onPress={()=>setPrivacy(false)}/>}><Icon name="pin" size={44} color={t.accent}/><Txt serif size={36}>Your places. Your privacy.</Txt><Txt>We use the arrival area around each place you save to notice when you arrive and leave. Those visits help count your sessions without a check-in.</Txt><Txt>Location samples are kept only during a possible visit to a saved place. Outside those areas, we don’t keep a location trail. Arrival areas can include the pavement or car park, so a visit is an estimate, not proof of exercise.</Txt><Txt>Your exact times and location samples stay private. Friends see your session summary so they can cheer you on.</Txt><Txt>You can pause tracking in Account, remove a saved place, or turn off location access in iPhone Settings.</Txt></Screen>;
  if(d.step===-1)return <Screen footer={<Button title="Continue" onPress={advance}/>}><Pressable accessibilityLabel="Back to Welcome" onPress={()=>change({step:0})} style={{padding:10,alignSelf:"flex-start"}}><Icon name="back"/></Pressable><Logo/><Txt serif size={38}>How it works.</Txt>{[["Save your studio or gym.","Drop a pin on the place you go. That's the only spot we ever pay attention to.","pin"],["Go.","When you arrive, the clock starts. When you leave, it stops. That's your session — no typing.","clock"],["It's counted.","Sessions add up to your weekly goal and your streak, and your friends see them.","flame"]].map(([title,body,icon],i)=><Card key={title} style={{gap:12}}><Row><Avatar own name={String(i+1)} size={36}/><Icon name={icon!} color={t.accent}/></Row><Txt serif size={26}>{title}</Txt><Txt>{body}</Txt></Card>)}<Txt muted size={13}>We’ll ask for your location once, on the next few screens.</Txt></Screen>;
  if (d.step === 0) return <Screen footer={footer} style={{ gap: 10 }}>
    <Logo size={25} /><Txt serif size={36}>Go to the gym or a class. Forget the tracking.</Txt><Txt muted size={17}>Other apps make you write every workout down. This one does it for you — without breaking a sweat.</Txt>
    <Row style={{ alignItems: "stretch" }}><Card style={{ flex: 1, padding: 12 }}><Txt bold size={11}>Other apps</Txt>{["Type your workout", "Log each set", "Remember to check in"].map(s => <Txt key={s} size={14} muted style={{ textDecorationLine: "line-through", marginTop: 6 }}>×  {s}</Txt>)}</Card><Card dark style={{ flex: 1, padding: 12 }}><Txt size={11} style={{ color: "#decbd3" }} bold>ClassStreak</Txt><Txt size={20} bold style={{ color: "#fff" }}>Just go.</Txt><Txt size={11} style={{ color: "#fff" }}>Reformer · 52 min · counted</Txt><View style={{ marginTop: 6, backgroundColor: "#ffffff22", borderRadius: 20, padding: 4 }}><Txt size={10} bold style={{ color: "#fff", textAlign: "center" }}>✓  2/3 this week</Txt></View></Card></Row>
    <Card style={{gap:13}}><Txt serif size={24}>Your friends will know if you skipped — and cheer you on.</Txt><Txt muted size={13}>A weekly league with the people who’d actually notice.</Txt><Card style={{backgroundColor:t.paper,padding:12,borderRadius:16}}><Row><Avatar name="Maya"/><View style={{flex:1}}><Txt bold size={13}>Maya usually goes Tuesdays</Txt><Txt muted size={11}>Nothing logged yet</Txt></View></Row><View style={{alignSelf:"flex-end",marginTop:8}}><Chip title="Nudge" selected/></View></Card><Row style={{alignItems:"flex-start"}}><Avatar name="Priya" size={26}/><Txt size={14} style={{flex:1}}><Txt bold size={14}>Priya:</Txt> you got this — go tomorrow 💪</Txt></Row><Txt muted size={10}>Example activity</Txt></Card>
  </Screen>;
  return <Screen footer={footer} style={{ gap: 16 }}>
    <Row><Txt muted size={12}>{steps[d.step]}</Txt><View style={{ flex: 1 }} /><Pressable onPress={() => change({ step: d.step===1?-1:Math.max(0,d.step-1) })} accessibilityLabel="Previous step" hitSlop={14}><Icon name="back" size={16} /></Pressable></Row>
    <View style={{ gap: 9 }}><Txt serif size={35}>{titles[d.step]}</Txt>{!!descriptions[d.step] && <Txt muted size={14}>{descriptions[d.step]}</Txt>}</View>
    {d.step === 1 && <><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>{activities.map(a => {
      const selected = d.selected.includes(a.key); return <Pressable key={a.key} accessibilityRole="checkbox" accessibilityState={{ checked: selected }} onPress={() => { const selectedKeys = selected ? d.selected.filter(k => k !== a.key) : [...d.selected, a.key]; change({ selected: selectedKeys, goals: draftGoals(selectedKeys, d.goals) }); }} style={{ width: "31.5%", minHeight: 91, padding: 13, borderRadius: 18, borderWidth: 1, borderColor: selected ? t.ink : t.line, backgroundColor: selected ? t.tint : t.card, justifyContent: "space-between" }}><Row><Icon name={a.icon} size={19} /><View style={{ flex: 1 }} />{selected && <Icon name="check" size={14} />}</Row><Txt size={13} bold>{a.label}</Txt></Pressable>;
    })}{d.selected.filter(key=>key.startsWith("custom:")).map(key=><Chip key={key} title={activity(key).label} selected onPress={()=>change({selected:d.selected.filter(k=>k!==key),goals:Object.fromEntries(Object.entries(d.goals).filter(([k])=>k!==key))})}/>)}</View><CustomActivity onAdd={key=>{const selected=[...new Set([...d.selected,key])];change({selected,goals:draftGoals(selected,d.goals)});}}/><Txt size={12} muted>Any gym counts for Gym. Studios count for the rest. You can add more later.</Txt></>}
    {d.step === 2 && <>{d.selected.slice(0, 2).map(key => <View key={key} style={{ gap: 8 }}><Row><Icon name={activity(key).icon} size={18} /><Txt serif size={22}>{activity(key).short}</Txt></Row>{[1, 2, 3, 4].map((v, i) => <Pressable key={v} accessibilityRole="radio" accessibilityState={{ selected: d.goals[key] === v }} onPress={() => change({ goals: { ...d.goals, [key]: v } })} style={{ minHeight: 49, borderRadius: 15, borderWidth: 1, borderColor: d.goals[key] === v ? t.ink : t.line, backgroundColor: d.goals[key] === v ? t.tint : t.card, paddingHorizontal: 16, justifyContent: "center" }}><Row><Txt serif size={25} style={{ width: 38 }}>{v === 4 ? "4+" : v}</Txt><Txt bold size={13} style={{ flex: 1 }}>{["Once a week", "Twice a week", "Three times a week", "Four or more"][i]}</Txt>{d.goals[key] === v && <Icon name="check" size={16} />}</Row></Pressable>)}</View>)}<Card><Txt muted size={12}>{d.selected.length > 2 ? `You picked ${d.selected.length} things. Set up the rest in your profile after this. ` : ""}Your weekly goal is the total: {total} sessions.</Txt></Card></>}
    {d.step===3&&<>{places.length>0&&<><Txt bold>Your places</Txt>{places.map((p,i)=><Card key={p.name+i}><Row><Icon name="check" color={t.accent}/><Txt bold style={{flex:1}}>{p.name}</Txt></Row></Card>)}<Button secondary icon="plus" title={addingPlace?"Done adding":"Add another"} onPress={()=>setAddingPlace(!addingPlace)}/></>}{(!places.length||addingPlace)&&search}</>}
    {d.step===4&&<ActivitySchedules selected={d.selected} schedules={d.schedules??d.selected.map(activity_key=>({activity_key,days:d.days,time:d.time}))} onChange={schedules=>change({schedules,days:[...new Set(schedules.flatMap(s=>s.days))]})}/>}
    {d.step === 5 && <><Txt bold size={15}>Turn on location and all <Txt bold style={{ color: t.accent, textDecorationLine: "underline" }}>three</Txt> of these just happen.</Txt><Card style={{backgroundColor:t.tint,gap:8}}><Icon name="pin" color={t.accent}/><Txt bold size={17}>Choose <Txt bold size={17} style={{color:t.accent}}>“ALWAYS”</Txt> so it works while your phone is in your bag.</Txt></Card>{[
      ["Your workout logs itself", "Walk in, work out, walk out. It's on the board."],
      ["Post it in one tap", "A sticker with your stats, ready for your story."],
      ["Friends keep you honest", "A weekly league, and a nudge when you skip."],
    ].map(([title, body], i) => <Card key={title} style={{ backgroundColor: t.paper, gap: 10, padding: 13 }}><Row style={{ alignItems: "flex-start" }}><Avatar own name={String(i + 1)} size={26} /><View style={{ flex: 1 }}><Txt bold size={14}>{title}</Txt><Txt muted size={11}>{body}</Txt></View></Row>{i === 0 ? <Card style={{ padding: 11, borderRadius: 15 }}><Row><Icon name="reformer" /><View style={{ flex: 1 }}><Txt bold size={12}>Reformer · 52 min</Txt><Txt size={10} muted>Club Pilates Summerlin · logged</Txt></View><Icon name="check" color={t.accent} /></Row></Card> : i === 1 ? <Card dark style={{alignItems:"center",gap:12,padding:18}}><Txt bold size={18} style={{color:"#fff",textAlign:"center"}}>Reformer Pilates</Txt><Row style={{width:"100%",justifyContent:"space-around"}}>{[["Time","52m"],["This week","2/3"],["Streak","6 wk"]].map(([label,value])=><View key={label} style={{alignItems:"center",gap:3}}><Txt size={11} style={{color:"#fff"}}>{label}</Txt><Txt bold size={20} style={{color:"#fff"}}>{value}</Txt></View>)}</Row><Logo white size={17}/></Card> : ["Priya", "You", "Ifti"].map((name, j) => <Row key={name} style={{ padding: 6, backgroundColor: j === 1 ? t.tint : t.card, borderRadius: 10 }}><Avatar name={name} size={22} /><Txt bold size={12} style={{ flex: 1 }}>{name}</Txt><Txt serif size={20}>{3 - j}</Txt></Row>)}</Card>)}<Pressable accessibilityRole="link" onPress={()=>setPrivacy(true)} style={{padding:12}}><Txt size={13} style={{color:t.accent,textAlign:"center",textDecorationLine:"underline"}}>How we handle your location</Txt></Pressable></>}
    {d.step === 6 && (["blush", "sage", "clay"] as const).map(name => <Pressable key={name} accessibilityRole="radio" accessibilityState={{ selected: d.theme === name }} onPress={() => change({ theme: name })}><Card style={{ minHeight: 148, borderColor: d.theme === name ? t.ink : t.line }}><Row style={{ flex: 1, gap: 18 }}><View style={{ width: 83, padding: 8, gap: 6, borderRadius: 16, borderWidth: 1, borderColor: t.line, backgroundColor: themes[name].paper }}><Txt serif size={11} style={{ color: themes[name].ink }}>ClassStreak.</Txt><View style={{ backgroundColor: themes[name].ink, borderRadius: 8, padding: 6 }}><Txt bold style={{ color: "#fff" }}>2/3</Txt><Row style={{ gap: 3 }}>{[0, 1, 2].map(x => <View key={x} style={{ width: 8, height: 8, borderRadius: 6, backgroundColor: x < 2 ? themes[name].accent : "#ffffff55" }} />)}</Row></View><View style={{ backgroundColor: themes[name].tint, height: 13, borderRadius: 9 }} /><View style={{ backgroundColor: themes[name].accent, height: 16, borderRadius: 9 }} /></View><View style={{ flex: 1, gap: 8 }}><Txt bold>{name[0]!.toUpperCase() + name.slice(1)}</Txt><Row style={{ gap: 5 }}>{["paper", "tint", "accent", "ink"].map(token => <View key={token} style={{ width: 21, height: 21, borderRadius: 12, backgroundColor: themes[name][token as keyof typeof t], borderWidth: 1, borderColor: t.line }} />)}</Row></View>{d.theme === name ? <View style={{ backgroundColor: t.accent, borderRadius: 20, padding: 5 }}><Icon name="check" size={16} color="#fff" /></View> : <View style={{ width: 26, height: 26, borderRadius: 20, borderColor: t.line, borderWidth: 1 }} />}</Row></Card></Pressable>)}
    {d.step === 7 && <><Input label="First name" value={d.first_name} onChange={first_name => change({ first_name })} /><Input label="Last name (optional)" value={d.last_name} onChange={last_name => change({ last_name })} /></>}
    {d.step === 8 && ["Woman", "Man", "Non-binary", "Prefer not to say"].map(gender => <Pressable key={gender} accessibilityRole="radio" accessibilityState={{ selected: d.gender === gender }} onPress={() => change({ gender })}><Card style={{ backgroundColor: d.gender === gender ? t.tint : t.card, borderColor: d.gender === gender ? t.ink : t.line, minHeight: 60, justifyContent: "center" }}><Txt bold>{gender}</Txt></Card></Pressable>)}
    {d.step === 9 && <><Card style={{ gap: 9 }}><Txt muted size={11} bold>WHAT YOU SET UP</Txt><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 6 }}>{d.selected.map(key => <Chip key={key} title={activity(key).label} icon={activity(key).icon} selected />)}<Chip title={`${total} sessions a week`} selected />{places.map((p,i)=><Chip key={p.name+i} title={p.name} icon="pin" selected/>)}{d.days.length > 0 && <Chip title={d.days.map(i => fullDays[i]!.slice(0, 3)).join(" · ")} selected />}<Chip title={d.theme[0]!.toUpperCase() + d.theme.slice(1)} selected /></View></Card><View style={{ flex: 1, minHeight: 30 }} />{account}</>}
  </Screen>;
}
