import {Confetti,SoftPressable} from "./motion";
import React,{useRef,useState,useEffect} from "react";
import {Image,Modal,PanResponder,Pressable,StyleSheet,View,useWindowDimensions} from "react-native";
import {CameraView,useCameraPermissions} from "expo-camera";
import * as ImagePicker from "expo-image-picker";
import {captureRef} from "react-native-view-shot";
import {BlurView} from "expo-blur";
import {type Snapshot} from "./model";
import {progress} from "./engine";
import {Avatar,Button,Card,Empty,Icon,Input,Logo,Row,Screen,Txt,useTheme} from "./ui";
import {Sticker,type Action} from "./SessionScreens";
import {queuePhoto,saveToPhotos,sharePhoto} from "./photos";
export function Post({snapshot:s,sessionId,action,now,onSaved}:{snapshot:Snapshot;sessionId?:string;action:Action;now:Date;onSaved:()=>Promise<void>}){
 const t=useTheme();const [permission,requestPermission]=useCameraPermissions();const camera=useRef<CameraView>(null);const image=useRef<View>(null);
 const [uri,setUri]=useState<string|null>(null);const [note,setNote]=useState("");const [busy,setBusy]=useState(false);const [stylesOpen,setStylesOpen]=useState(false);const [story,setStory]=useState(false);
 const {width,height}=useWindowDimensions();const canvasWidth=width;const canvasHeight=Math.max(330,Math.min(height-275,width*1.48));const stickerWidth=Math.min(width-40,350);
 const [position,setPosition]=useState({x:20,y:canvasHeight*.24,scale:1});const start=useRef(position);const distance=useRef(0);
 // PanResponder stores callbacks; these refs are read only by touch events, never by create().
 // eslint-disable-next-line react-hooks/refs
 const responder=PanResponder.create({onStartShouldSetPanResponder:()=>true,onMoveShouldSetPanResponder:()=>true,onPanResponderGrant:e=>{start.current=position;const a=e.nativeEvent.touches;distance.current=a.length>1?Math.hypot(a[0]!.pageX-a[1]!.pageX,a[0]!.pageY-a[1]!.pageY):0;},onPanResponderMove:(e,g)=>{const touches=e.nativeEvent.touches;const scale=touches.length>1&&distance.current>0?Math.max(.6,Math.min(1.4,start.current.scale*Math.hypot(touches[0]!.pageX-touches[1]!.pageX,touches[0]!.pageY-touches[1]!.pageY)/distance.current)):start.current.scale;setPosition({x:Math.max(0,Math.min(canvasWidth-stickerWidth,start.current.x+g.dx)),y:Math.max(0,Math.min(canvasHeight-210,start.current.y+g.dy)),scale});}});
 const stats=progress(s.sessions,s.weeks,s.goals,s.profile.tz,now);const session=s.sessions.find(x=>x.id===sessionId&&!x.removed_at)??s.sessions.find(x=>!x.removed_at&&Date.parse(x.started_at)>=now.getTime()-7*86400000);
 const run=(fn:()=>Promise<void>)=>{setBusy(true);void fn().catch(error=>action("error",{error})).finally(()=>setBusy(false));};
 const pick=async()=>{const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],quality:.9});if(!result.canceled){setUri(result.assets[0]!.uri);setStory(false);}};
 const capture=async()=>{const photo=await camera.current?.takePictureAsync({quality:.9});if(photo){setUri(photo.uri);setStory(false);}};
 const exportImage=async()=>{if(!uri)throw new Error("Take or choose a photo first.");return captureRef(image,{format:"jpg",quality:.92,result:"tmpfile",width:1080});};
 const finish=async(destination:"share"|"save"|"close")=>{
  if(!session)return;const result=await exportImage();const synced=await queuePhoto(result,session.id,note);await onSaved();
  if(destination==="save")await saveToPhotos(result);else{action("message",{text:destination==="close"?"Choose Instagram, then select Close Friends there. Paste the copied link into a link sticker.":"Choose Instagram in the share sheet. Paste the copied invite into a link sticker."});await sharePhoto(result,s.profile.invite_code);}
  setUri(result);setStory(true);if(!synced)action("message",{text:"Your session photo is saved privately on this phone and will upload when you reconnect."});
 };
 if(!session)return <Screen><Empty title="A session worth sharing." body="No session in the last seven days. Add a missed visit to make your sticker." action="Add a session" onPress={()=>action("navigate",{pane:"manual"})}/><Button secondary title="Back" onPress={()=>action("navigate",{pane:"home"})}/></Screen>;
 return <><Screen style={{padding:0,gap:0}} footer={<><Button title={story?"Share again":"Share to your story"} disabled={!uri||busy} onPress={()=>run(()=>finish("share"))}/><Row><View style={{flex:1}}><Button secondary title="Close friends only" disabled={!uri||busy} onPress={()=>run(()=>finish("close"))}/></View><View style={{flex:1}}><Button secondary title="Just save it" disabled={!uri||busy} onPress={()=>run(()=>finish("save"))}/></View></Row></>}>
  <View style={{backgroundColor:t.ink,padding:14}}><Row><Pressable accessibilityLabel="Close Post" onPress={()=>action("navigate",{pane:"home"})} style={{padding:9,backgroundColor:"#ffffff22",borderRadius:40}}><Icon name="x" color="#fff"/></Pressable><Txt bold size={14} style={{color:"#fff",flex:1,textAlign:"center"}}>{story?"On your story":"Post today’s session"}</Txt><View style={{width:40}}/></Row></View>
  <View ref={image} collapsable={false} style={{height:canvasHeight,width:canvasWidth,backgroundColor:t.ink,overflow:"hidden"}}>
   {uri?<Image source={{uri}} style={StyleSheet.absoluteFill} resizeMode="cover"/>:permission?.granted?<CameraView ref={camera} facing="back" style={StyleSheet.absoluteFill}/>:<View style={{padding:25,gap:15}}><Txt serif size={32} style={{color:"#fff"}}>Your session. Your story.</Txt><Button title="Turn on camera" onPress={()=>run(async()=>{await requestPermission();})}/><Button secondary title="Choose a photo" onPress={()=>run(pick)}/></View>}
   {(uri||permission?.granted)&&!story&&<View {...responder.panHandlers} accessibilityLabel="Session sticker. Drag to move, pinch to resize." style={{position:"absolute",left:position.x,top:position.y,width:stickerWidth,transform:[{scale:position.scale}],borderRadius:24,overflow:"hidden"}}><BlurView tint="dark" intensity={35} style={StyleSheet.absoluteFill}/><Sticker session={session} count={stats.count} goal={stats.goal} streak={stats.streak} frosted/></View>}
  </View>
  {story?<View style={{padding:20,gap:12,backgroundColor:t.ink}}><Row><Avatar name={s.profile.first_name}/><Txt bold style={{color:"#fff"}}>Your story preview</Txt></Row><Button title="Join me on ClassStreak" icon="link" onPress={()=>action("copy_invite")}/><Txt size={12} style={{color:"#fff"}}>The image is ready. Add the copied link in Instagram so friends can find you.</Txt></View>:<><View style={{marginTop:-76,height:76,backgroundColor:"#00000033",padding:12}}><Row style={{justifyContent:"space-around"}}><Pressable accessibilityLabel="Choose a photo" onPress={()=>run(pick)} style={{padding:13}}><Icon name="share" color="#fff"/></Pressable><SoftPressable accessibilityLabel={uri?"Retake photo":"Take photo"} disabled={busy} onPress={()=>uri?setUri(null):run(capture)} style={{width:68,height:68,borderRadius:40,backgroundColor:t.accent,borderWidth:7,borderColor:"#fff",marginTop:-10}}/><Pressable accessibilityLabel="Sticker styles" onPress={()=>setStylesOpen(true)} style={{padding:13}}><Icon name="star" color="#fff"/></Pressable></Row></View><View style={{padding:16,gap:8}}><Txt muted size={11}>Drag the sticker anywhere. Pinch to resize.</Txt><Input label="Add a note (optional)" value={note} onChange={v=>setNote(v.slice(0,240))}/></View></>}
 </Screen><Modal visible={stylesOpen} transparent animationType="none" onRequestClose={()=>setStylesOpen(false)}><View style={{flex:1,justifyContent:'flex-end',backgroundColor:'#00000066'}}><View style={{backgroundColor:t.paper,padding:24,paddingBottom:36,borderTopLeftRadius:28,borderTopRightRadius:28,gap:18}}><Txt serif size={28}>More styles coming</Txt><Button title="Done" onPress={()=>setStylesOpen(false)}/></View></View></Modal></>;
}
const openedMilestones=new Set<string>();
export function Celebration({snapshot:s,action,now,milestone,celebrate=true}:{snapshot:Snapshot;action:Action;now:Date;milestone?:number;celebrate?:boolean}){
 const t=useTheme();const image=useRef<View>(null);const stats=progress(s.sessions,s.weeks,s.goals,s.profile.tz,now);
 const celebrationKey=s.profile.id+":"+milestone;const [firstOpen]=useState(()=>!openedMilestones.has(celebrationKey));useEffect(()=>{if(milestone)openedMilestones.add(celebrationKey);},[milestone,celebrationKey]);
 const earned=milestone?s.sessions.filter(x=>x.counted&&!x.removed_at).sort((a,b)=>a.started_at.localeCompare(b.started_at))[milestone-1]:undefined;
 const headline=milestone===1?"Congrats on your first class!":milestone===10?"Ten classes. Look at you go!":milestone===25?"25 classes. A habit worth celebrating.":milestone===50?"Fifty times you showed up.":milestone===100?"100 classes. All yours.":`${milestone} classes. Keep going!`;
 const share=()=>{void captureRef(image,{format:"jpg",quality:.95,width:1080}).then(uri=>sharePhoto(uri,s.profile.invite_code)).catch(error=>action("error",{error}));};
 return <View style={{gap:20}}><View ref={image} collapsable={false} style={{padding:22,paddingVertical:34,gap:20,alignItems:"center",backgroundColor:t.paper,borderRadius:22}}><Logo/><Icon name={milestone?"trophy":"flame"} size={82} color={t.accent}/><Txt serif size={36} style={{textAlign:"center"}}>{milestone?headline:`${stats.count} of ${stats.goal}.`}</Txt><Txt size={16} style={{textAlign:"center"}}>{milestone===1?"One good start. More good days ahead.":milestone?"Every one started with showing up.":"That was your week."}</Txt><Card dark><Txt bold size={22} style={{color:"#fff",textAlign:"center"}}>{milestone?`${milestone} ${milestone===1?"class":"classes"} counted`:`${stats.streak} weeks in a row`}</Txt></Card><Txt muted style={{textAlign:"center"}}>{earned?new Date(earned.started_at).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric",timeZone:s.profile.tz}):"Your week, one session at a time."}{earned?.source==="seed"?" · Demo milestone":""}</Txt></View>{milestone&&celebrate&&firstOpen&&<Confetti accent={t.accent} tint={t.tint}/>}<Button title="Share your card" icon="share" onPress={share}/><Button secondary title="Back" onPress={()=>action("navigate",{pane:"profile"})}/></View>;
}
