import {ActiveWorkout} from "./ActiveWorkout";
import type {Candidate} from "./engine";
import {ActivitySchedules,CustomActivity} from "./ActivitySetup";
import {SoftPressable,BouncePressable} from "./motion";
import React, {useState} from "react";
import {Pressable,View,Switch} from "react-native";
import {activity,activities,fullDays,type Schedule,type Snapshot,type ThemeName} from "./model";
import {progress,dayKey} from "./engine";
import {Avatar,Button,Card,Chart,Chip,Empty,Icon,Input,Logo,Ring,StreakFlame,Row,Screen,Txt,useTheme} from "./ui";
import {History,ManualSession,SessionDetails,type Action} from "./SessionScreens";
export type ProductProps={activeWorkout?:Candidate|null;busy?:boolean;snapshot:Snapshot;pane:string;action:Action;now?:Date;tracking?:string;extra?:(pane:string)=>React.ReactNode};
export function Product({activeWorkout=null,busy=false,snapshot:s,pane,action,now=new Date(),tracking,extra}:ProductProps){
 const t=useTheme();const [selectedWeek,setSelectedWeek]=useState<string|null>(null);const p=s.profile;const stats=progress(s.sessions,s.weeks,s.goals,p.tz,now);
 const tabs=[["home","Home","home"],["studios","Studios","studio"],["post","Post","camera"],["friends","Friends","friends"],["profile","Profile","person"]];
 const root=["home","studios","friends","profile"].includes(pane);const unread=s.inbox.filter(i=>!i.read_at).length;
 const navigate=(target:string)=>action("navigate",{pane:target});
 let body:React.ReactNode;
 if(pane==="home"){
  const latest=s.sessions.find(x=>!x.removed_at);const weekday=(new Date(dayKey(now,p.tz)+"T12:00:00Z").getUTCDay()+6)%7;const usual=s.usual_days.find(d=>d.weekday===weekday);
  const friends=s.friends.filter(f=>f.status==="accepted");const done=Number(friends.length>=3)+Number(s.sessions.some(x=>x.photo_url))+Number(!!latest)+Number(p.health_verify);
  body=<><ActiveWorkout compact candidate={activeWorkout} snapshot={s} action={action} busy={busy}/><Card><Row><Ring count={stats.count} goal={stats.goal}/><View style={{flex:1}}><Txt size={12} muted>Your week</Txt><Txt serif size={27}>{stats.count} of {stats.goal}{"\n"}sessions</Txt><Txt muted size={15}>{s.goals.filter(g=>g.goal>0).map(g=>`${activity(g.activity_key).short} ${s.sessions.filter(x=>x.week_key===stats.week&&x.activity_key===g.activity_key&&x.counted&&!x.removed_at&&Date.parse(x.started_at)<=now.getTime()).length}/${g.goal}`).join(" · ")}</Txt></View></Row><View style={{alignSelf:"flex-start",marginTop:14,backgroundColor:t.paper,borderRadius:99,paddingHorizontal:13,paddingVertical:7}}><Row style={{gap:6}}><StreakFlame streak={stats.streak} size={17} color={t.accent}/><Txt bold size={13}>{stats.streak}-week streak</Txt></Row></View></Card>
   {usual&&<Card dark><Row><View style={{backgroundColor:"#ffffff22",padding:12,borderRadius:14}}><Icon name="clock" color="#fff"/></View><View style={{flex:1}}><Txt bold size={15} style={{color:"#fff"}}>{fullDays[weekday]} is a {activity(usual.activity_key??s.goals[0]?.activity_key??"reformer").short} day</Txt><Txt size={12} style={{color:"#decbd3"}}>Usually around {usual.time_of_day==="morning"?"8 am":usual.time_of_day==="midday"?"12 pm":"6 pm"}</Txt></View></Row></Card>}
   {tracking&&<Pressable onPress={()=>tracking.includes("ettings")?action("open_settings"):navigate("account")}><Card style={{padding:12}}><Txt size={12}>{tracking}</Txt></Card></Pressable>}
   {done<4&&<><Row><Txt serif size={24} style={{flex:1}}>Keep going</Txt><Txt muted size={12}>{done} of 4 done</Txt></Row>{[
    {title:"Add 3 friends",detail:`${Math.min(friends.length,3)} of 3 · contacts, link or scan`,done:friends.length>=3,to:"add-friends"},
    {title:"Post your first sticker",detail:"Tap the camera below",done:s.sessions.some(x=>x.photo_url),to:"post"},
    {title:"Go to a session",detail:latest?"Logged itself":"Save your studio, then just go",done:!!latest,to:"history"},
    {title:"Connect Apple Watch",detail:"Optional · verify with Apple Health",done:p.health_verify,to:"health"},
   ].map(item=><Pressable key={item.title} onPress={()=>navigate(item.to)}><Card style={{padding:13,borderRadius:18}}><Row><View style={{width:28,height:28,borderRadius:20,borderWidth:1,borderColor:t.line,backgroundColor:item.done?t.accent:t.card,alignItems:"center",justifyContent:"center"}}>{item.done&&<Icon name="check" color="#fff" size={15}/>}</View><View style={{flex:1}}><Txt bold size={14} style={{textDecorationLine:item.done?"line-through":"none"}}>{item.title}</Txt><Txt muted size={11}>{item.detail}</Txt></View><Icon name="chevron" size={14}/></Row></Card></Pressable>)}</>}
   {latest?<Pressable accessibilityLabel="Open latest session" onPress={()=>navigate("session:"+latest.id)}><Card><Row><View style={{flex:1,gap:4}}><Txt muted size={11}>Latest</Txt><Txt bold>{latest.workout_label} · {latest.place_name??"Your saved place"}</Txt><Txt muted size={12}>{Math.floor(latest.duration_sec/60)} min · {latest.source==="simulated"?"simulated":latest.source==="seed"?"demo":latest.day_key===dayKey(now,p.tz)?"today":latest.day_key}</Txt></View><SoftPressable accessibilityLabel="Post latest session" onPress={()=>action("post",{id:latest.id})} style={{padding:14,borderRadius:16,backgroundColor:t.tint}}><Icon name="camera"/></SoftPressable></Row></Card></Pressable>:<Empty title="Your first session is ahead." body="We will count it after you leave a saved studio or gym." action="Your saved places" onPress={()=>navigate("places")}/>}
  </>;
 }else if(pane==="profile"){
  const milestones=[1,10,25,50,100];const next=milestones.find(n=>n>stats.lifetime)??250;
  body=<><Row><Avatar name={p.first_name} size={50}/><Txt serif size={28}>{p.first_name}</Txt></Row><Card style={{padding:0,overflow:"hidden"}}><Row style={{gap:0,alignItems:"stretch"}}>{[["Goal",`${stats.goal} / week`,"goals"],["Sessions",String(stats.lifetime),"history"],["Usual days",s.usual_days.length?[...new Set(s.usual_days.map(d=>fullDays[d.weekday]!.slice(0,3)))].join(" · "):"Set your days","days"]].map(([label,value,to],i)=><SoftPressable key={label} accessibilityRole="button" onPress={()=>navigate(to!)} style={{flex:1,padding:13,backgroundColor:i===0?t.accent:t.card,borderLeftWidth:i?1:0,borderColor:t.line,gap:8}}><Txt size={11} bold style={{color:i===0?"#fff":t.muted}}>{label}</Txt><Txt bold size={i===2?12:20} style={{color:i===0?"#fff":t.ink}}>{value}</Txt></SoftPressable>)}</Row></Card>
   <Card style={{gap:13}}><Row><StreakFlame streak={stats.streak} color={t.accent} size={25}/><View style={{flex:1}}><Txt serif size={28}>{stats.streak} {stats.streak===1?"week":"weeks"} in a row</Txt><Txt muted size={12}>Every week you hit your goal, the streak grows by 1.</Txt></View></Row><Row style={{gap:4,justifyContent:"space-between"}}>{stats.history.slice(-8).map((w,i)=><SoftPressable key={w.week} accessibilityLabel={`${w.week}: ${w.count} sessions`} onPress={()=>{setSelectedWeek(w.week);setTimeout(()=>setSelectedWeek(null),1200);}} style={{alignItems:"center",gap:5,flex:1,opacity:selectedWeek&&selectedWeek!==w.week?0.6:1}}><View style={{width:30,height:32,borderRadius:18,alignItems:"center",justifyContent:"center",backgroundColor:i===7?t.tint:w.hit?t.accent:t.card,borderWidth:1,borderColor:selectedWeek===w.week?t.accent:i===7?t.ink:t.line,shadowColor:t.accent,shadowOpacity:selectedWeek===w.week?0.45:0,shadowRadius:9,shadowOffset:{width:0,height:0}}}>{i===7?<Txt size={10}>{stats.count}/{stats.goal}</Txt>:<Icon name={w.hit?"check":"x"} size={14} color={w.hit?"#fff":t.muted}/>}</View><Txt size={8} muted>{i===7?"Now":new Date(w.week+"T12:00:00Z").toLocaleDateString("en-US",{month:"short",day:"numeric"})}</Txt></SoftPressable>)}</Row><Row style={{gap:7}}><Icon name="check" size={15} color={t.accent}/><Txt muted size={12} style={{flex:1}}>{selectedWeek?`${stats.history.find(w=>w.week===selectedWeek)?.count??0} sessions that week. You showed up.`:"Each check is a goal met. Keep showing up."}</Txt></Row></Card>
   <Card style={{gap:12}}><Txt bold size={14}>Sessions per week, last 12 weeks</Txt><Chart values={stats.history.map(w=>w.count)}/><Txt muted size={11}>Each bar is one week, oldest to newest.</Txt></Card>
   <Card style={{gap:13}}><Row><Txt bold size={14} style={{flex:1}}>Class milestones</Txt><Txt size={11} muted>{Math.max(0,next-stats.lifetime)} to your {next}{next===1?"st":"th"}</Txt></Row><Row style={{justifyContent:"space-between",gap:4}}>{milestones.map(n=><BouncePressable key={n} accessibilityLabel={n+" class milestone"} onPress={()=>{if(stats.lifetime>=n)navigate("milestone:"+n);}} style={{alignItems:"center",gap:5}}><View style={{backgroundColor:stats.lifetime>=n?t.accent:t.card,borderColor:stats.lifetime>=n?t.accent:t.line,borderWidth:1,borderRadius:16,padding:12}}><Icon name="trophy" color={stats.lifetime>=n?"#fff":t.muted}/></View><Txt size={10} bold style={{textAlign:"center"}}>{n}{"\n"}{n===1?"class":"classes"}</Txt></BouncePressable>)}</Row><View style={{height:8,backgroundColor:t.line,borderRadius:8}}><View style={{height:8,width:`${Math.min(100,stats.lifetime/next*100)}%`,backgroundColor:t.accent,borderRadius:8}}/></View></Card>
   <Button dark title="Your stats by studio and by day" icon="lock" onPress={()=>navigate("plus")}/><Txt size={11} muted style={{textAlign:"center"}}>ClassStreak+ · 14 days free</Txt>
   {[["History","history"],["Places","places"],["Goals","goals"],["Usual days","days"],["Look","look"],["Notifications","notifications"],["Apple Health","health"],["Account","account"]].map(([label,target])=><MenuRow key={target} title={label!} onPress={()=>navigate(target!)}/>)}
  </>;
 }else if(pane==="history")body=<History snapshot={s} action={action}/>;
 else if(pane==="manual")body=<ManualSession snapshot={s} action={action}/>;
 else if(pane.startsWith("session:")){const session=s.sessions.find(x=>x.id===pane.slice(8)&&!x.removed_at);body=session?<SessionDetails session={session} snapshot={s} stats={stats} action={action}/>:<Empty title="Session removed" body="Your weekly totals have been updated."/>;}
 else if(pane==="places")body=<><Txt serif size={32}>Your places</Txt><Txt muted size={13}>Your saved pins stay private.</Txt>{s.places.filter(p=>p.enabled).map(p=><Card key={p.id}><Row><Icon name={activity(p.activity_key).icon}/><View style={{flex:1}}><Txt bold>{p.name}</Txt><Txt muted size={12}>{activity(p.activity_key).label} · {p.radius_m} m</Txt></View></Row><Row style={{marginTop:10}}><Button small secondary title="Edit" onPress={()=>action("edit_place",{id:p.id})}/><Button small secondary title="Stop tracking here" onPress={()=>action("settings",{kind:"disable_place",payload:{id:p.id}})}/></Row></Card>)}<Button title="Add a studio or gym" icon="plus" onPress={()=>navigate("add-place")}/></>;
 else if(pane==="goals")body=<GoalsEditor snapshot={s} action={action}/>;
 else if(pane==="days")body=<DaysEditor snapshot={s} action={action}/>;
 else if(pane==="look")body=<><Txt serif size={32}>Pick your look</Txt>{(["blush","sage","clay"] as ThemeName[]).map(name=><Button key={name} secondary={p.theme!==name} title={name[0]!.toUpperCase()+name.slice(1)} onPress={()=>action("settings",{kind:"profile",payload:{theme:name}})}/>)}</>;
 else if(pane==="notifications")body=<><Txt serif size={32}>Notifications</Txt><Txt muted>Reminders arrive on this phone. Friend activity arrives in your inbox when you open ClassStreak.</Txt>{[["usual","Usual-day reminders"],["logged","Session logged"],["risk","Streak at risk"],["recap","Weekly recap"],["milestone","Milestones"],["nudge","Nudges"],["reaction","Reactions"],["comment","Comments"],["friend_request","Friend requests"]].map(([key,title])=><Card key={key}><Row><Txt style={{flex:1}}>{title}</Txt><Switch accessibilityLabel={title} value={p.notification_preferences[key!]!==false} onValueChange={value=>action("settings",{kind:"profile",payload:{notification_preferences:{[key!]:value}}})}/></Row></Card>)}<Txt muted size={12}>Quiet hours: 10 pm–7 am.</Txt><Button secondary title="Enable phone reminders" onPress={()=>action("enable_notifications")}/></>;
 else if(pane==="inbox")body=<><Row><Txt serif size={32} style={{flex:1}}>Your inbox</Txt><Button small secondary title="Mark read" onPress={()=>action("settings",{kind:"inbox_read",payload:{}})}/></Row>{!s.inbox.length&&<Empty title="All caught up." body="Friend requests, nudges and reactions will appear here."/>}{s.inbox.map(item=><Pressable key={item.id} onPress={()=>{action("settings",{kind:"inbox_read",payload:{id:item.id}});if(item.session_id)navigate("friends");}}><Card style={{borderColor:item.read_at?t.line:t.accent}}><Txt bold={!item.read_at}>{item.body}</Txt></Card></Pressable>)}</>;
 else if(pane==="account")body=<Account snapshot={s} action={action}/>;
 else body=extra?.(pane)??<Empty title={pane==="studios"?"Your studio":pane==="friends"?"Your friends":"Your session"} body={pane==="studios"?"Save a studio to see your visits here.":"Your private account is ready."} action={pane==="studios"?"Add a studio or gym":"Back to Home"} onPress={()=>navigate(pane==="studios"?"add-place":"home")}/>;
 if(pane.startsWith("session:"))return <View style={{flex:1,backgroundColor:t.ink,justifyContent:"flex-end"}}><View style={{backgroundColor:t.paper,borderTopLeftRadius:28,borderTopRightRadius:28,height:"80%",maxHeight:"85%",paddingTop:5}}><Pressable accessibilityRole="button" accessibilityLabel="Close session" onPress={()=>navigate("home")} style={{height:24,alignItems:"center",justifyContent:"center"}}><View style={{width:40,height:4,borderRadius:3,backgroundColor:t.line}}/></Pressable><Screen style={{paddingTop:4,paddingBottom:20}}>{body}</Screen></View></View>;
 const selected=pane==="friends"||pane==="add-friends"?"friends":pane==="studios"?"studios":["home","post"].includes(pane)?pane:"profile";
 return <View style={{flex:1,backgroundColor:t.paper}}><View style={{paddingHorizontal:20,paddingTop:16,paddingBottom:12}}>{root?<Row><Logo size={26}/><View style={{flex:1}}/>{pane==="home"&&<Pressable accessibilityLabel={`Inbox, ${unread} unread`} onPress={()=>navigate("inbox")} style={{padding:10,borderRadius:99,backgroundColor:t.card,borderWidth:1,borderColor:t.line}}><Icon name="bell" size={18}/>{unread>0&&<View style={{position:"absolute",right:-3,top:-3,backgroundColor:t.accent,borderRadius:10,paddingHorizontal:4}}><Txt size={9} bold style={{color:"#fff"}}>{unread}</Txt></View>}</Pressable>}{pane==="friends"&&<Pressable accessibilityLabel="Add friends" onPress={()=>navigate("add-friends")} style={{padding:9,borderRadius:99,backgroundColor:t.card}}><Icon name="plus" size={18}/></Pressable>}<Pressable accessibilityLabel="Your profile" onPress={()=>navigate("profile")}><Avatar name={p.first_name}/></Pressable></Row>:<Row><Pressable accessibilityLabel="Back" onPress={()=>navigate("profile")} style={{padding:8}}><Icon name="back"/></Pressable><View style={{flex:1}}/><Logo size={22}/><View style={{flex:1}}/><View style={{width:36}}/></Row>}</View><Screen key={pane} style={{paddingTop:4,gap:13,paddingBottom:32}}>{body}</Screen>
  <View style={{height:71,borderTopWidth:1,borderColor:t.line,backgroundColor:t.card,flexDirection:"row",alignItems:"center",paddingTop:5}}>{tabs.map(([target,title,icon])=>target==="post"?<View key={target} style={{flex:1,alignItems:"center"}}><SoftPressable accessibilityRole="button" accessibilityLabel="Post a session" onPress={()=>navigate("post")} style={{width:68,height:68,borderRadius:50,backgroundColor:t.accent,borderWidth:5,borderColor:t.card,alignItems:"center",justifyContent:"center",marginTop:-26}}><Icon name="camera" color="#fff" size={24}/></SoftPressable></View>:<Pressable key={target} accessibilityRole="tab" accessibilityState={{selected:selected===target}} accessibilityLabel={title} onPress={()=>navigate(target!)} style={{flex:1,alignItems:"center",gap:3,minHeight:54,justifyContent:"center"}}><View style={{borderRadius:20,paddingHorizontal:13,paddingVertical:4,backgroundColor:selected===target?t.tint:"transparent"}}><Icon name={icon!} size={19}/></View><Txt size={10} bold={selected===target}>{title}</Txt></Pressable>)}</View>
 </View>;
}
export function MenuRow({title,onPress}:{title:string;onPress:()=>void}){return <Pressable onPress={onPress}><Card style={{padding:14,borderRadius:16}}><Row><Txt style={{flex:1}}>{title}</Txt><Icon name="chevron" size={15}/></Row></Card></Pressable>;}
function GoalsEditor({snapshot:s,action}:{snapshot:Snapshot;action:Action}){
 const [goals,setGoals]=useState(s.pending_goals.length?s.pending_goals:s.goals);const [more,setMore]=useState(false);
 const add=(key:Schedule['activity_key'])=>{if(!goals.some(g=>g.activity_key===key))setGoals([...goals,{activity_key:key,goal:1}]);};
 return <><Txt serif size={32}>Your weekly goals</Txt><Txt muted>Make space for what you love. Changes start next Monday.</Txt>{goals.map(g=><Card key={g.activity_key} style={{gap:10}}><Row><Icon name={activity(g.activity_key).icon}/><Txt serif size={23} style={{flex:1}}>{activity(g.activity_key).label}</Txt></Row>{[1,2,3,4].map(n=><Chip key={n} title={n===4?"4+ · Four or more":`${n} · ${n===1?"Once":n===2?"Twice":"Three times"} a week`} selected={g.goal===n} onPress={()=>setGoals(goals.map(x=>x.activity_key===g.activity_key?{...x,goal:n}:x))}/>)}</Card>)}<Button secondary icon="plus" title="Add more" onPress={()=>setMore(!more)}/>{more&&<><Row style={{flexWrap:"wrap"}}>{activities.filter(a=>!goals.some(g=>g.activity_key===a.key)).map(a=><Chip key={a.key} title={a.label} onPress={()=>add(a.key)}/>)}</Row><CustomActivity onAdd={add}/></>}<Button title="Save for next week" onPress={()=>action("settings",{kind:"goals",payload:{goals}})}/></>;
}
function DaysEditor({snapshot:s,action}:{snapshot:Snapshot;action:Action}){
 const selected=(s.pending_goals.length?s.pending_goals:s.goals).map(g=>g.activity_key);
 const [schedules,setSchedules]=useState<Schedule[]>(selected.map(activity_key=>({activity_key,days:s.usual_days.filter(d=>!d.activity_key||d.activity_key===activity_key).map(d=>d.weekday),time:s.usual_days.find(d=>!d.activity_key||d.activity_key===activity_key)?.time_of_day??"evening"})));
 return <><Txt serif size={32}>Your usual days</Txt><Txt muted>A little room in your week for each thing you do.</Txt><ActivitySchedules selected={selected} schedules={schedules} onChange={setSchedules}/><Button title="Save usual days" onPress={()=>action("settings",{kind:"days",payload:{schedules}})}/></>;
}
function Account({snapshot:s,action}:{snapshot:Snapshot;action:Action}){
 const [first,setFirst]=useState(s.profile.first_name);const [last,setLast]=useState(s.profile.last_name);const [phone,setPhone]=useState("");const [taps,setTaps]=useState(0);
 return <><Txt serif size={32}>Account</Txt><Input label="First name" value={first} onChange={setFirst}/><Input label="Last name" value={last} onChange={setLast}/><Button title="Save name" onPress={()=>action("settings",{kind:"profile",payload:{first_name:first,last_name:last}})}/>
  <Input label="Phone number (optional, with country code)" value={phone} onChange={setPhone} keyboard="phone-pad"/><Txt muted size={12}>{s.profile.phone_set?"Your number is set up for finding friends.":"Add a number to find friends through contacts."} Your number is never shown to friends.</Txt><Button secondary title="Save phone number" onPress={()=>action("phone",{phone})}/>
  {[["share_place_name","Share place names with friends"],["show_on_board","Show me on studio boards"]].map(([key,title])=><Card key={key}><Row><Txt style={{flex:1}}>{title}</Txt><Switch accessibilityLabel={title} value={!!s.profile[key as "share_place_name"|"show_on_board"]} onValueChange={v=>action("settings",{kind:"profile",payload:{[key!]:v}})}/></Row></Card>)}
  <Button title="Start automatic tracking" onPress={()=>action("start_tracking")}/><Button secondary title="Pause tracking" onPress={()=>action("stop_tracking")}/>
  <MenuRow title="Timezone" onPress={()=>action("timezone")}/><MenuRow title="Terms and privacy" onPress={()=>action("privacy")}/>
  {s.sessions.some(x=>x.source==="seed")&&<Card style={{gap:10}}><Txt bold>Walkthrough demo data</Txt><Txt muted size={12}>Sample sessions and people help you explore. Your real visits stay separate.</Txt><Button secondary small title="Remove demo data" onPress={()=>action("remove_demo")}/></Card>}<Button secondary title="Sign out" onPress={()=>action("sign_out")}/><Button secondary title="Delete account" onPress={()=>action("delete_account")}/>
  <Pressable accessibilityLabel="Version 2.0.0. Tap five times for Debug." onPress={()=>{const count=taps+1;setTaps(count);if(count>=5){setTaps(0);action("navigate",{pane:"debug"});}}} style={{padding:16}}><Txt size={12} muted style={{textAlign:"center"}}>ClassStreak 2.0.0</Txt></Pressable>
 </>;
}
