import React,{useEffect,useState} from 'react';
import {Alert,Modal,Pressable,ScrollView,Switch,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {activities,activity,fullDays,safeMessage,type ActivityKey,type Snapshot} from './model';
import {dayKey,shiftDay} from './engine';
import {Button,Card,Chip,Icon,Input,Row,Txt,useTheme} from './ui';
import {ActivityArt} from './ActivityArt';
import {CustomActivity} from './ActivitySetup';
import {PlanTimePicker} from './PlanTimePicker';
import {emptyPlanning,formatPlanTime,periodTime,removePlannedWorkout,restorePlannedWorkout,savePlannedWorkout,weekCalendar,weekdayOf,workoutsOn,type PlannedWorkout,type WeeklyPlanning} from './planning';
import {loadWeeklyPlanning,saveWeeklyPlanning} from './planningStore';
import {enableNotifications,scheduleReminders} from './notifications';

function readableDay(day:string){return new Intl.DateTimeFormat('en-US',{weekday:'long',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(day+'T12:00:00Z'));}
const shortDay=(day:string)=>new Intl.DateTimeFormat('en-US',{weekday:'short',timeZone:'UTC'}).format(new Date(day+'T12:00:00Z'));

export function WeeklyPlan({snapshot:s,now=new Date()}:{snapshot:Snapshot;now?:Date}){
 const t=useTheme();const today=dayKey(now,s.profile.tz);const [pickedDay,setSelected]=useState<string|null>(null);const selected=pickedDay??today;const [plan,setPlan]=useState<WeeklyPlanning>(emptyPlanning);const [loaded,setLoaded]=useState(false);const [editing,setEditing]=useState<PlannedWorkout|null>(null);const [notice,setNotice]=useState('');
 useEffect(()=>{let active=true;void loadWeeklyPlanning(s).then(value=>{if(active){setPlan(value);setLoaded(true);}}).catch(e=>{if(active)setNotice(safeMessage(e));});return()=>{active=false;};},[s]);
 const days=weekCalendar(selected);const workouts=workoutsOn(plan,selected);const removed=plan.overrides.filter(o=>o.day===selected&&o.skipped);const completed=s.sessions.filter(x=>x.day_key===selected&&!x.removed_at&&x.source!=='seed'&&x.source!=='simulated');
 const start=days[0]!;const end=days[6]!;const month=(day:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(day+'T12:00:00Z'));
 const persist=async(value:WeeklyPlanning)=>{await saveWeeklyPlanning(s.profile.id,value);setPlan(value);await scheduleReminders(s);};
 const add=()=>{const key=s.goals[0]?.activity_key??'gym';setEditing({id:`extra:${selected}:${Date.now()}`,day:selected,activity_key:key,time:null,period:'evening',focus:'',reminder:true,recurring:false,changed:false});};
 return <View style={{gap:21}}>
  <Row><Txt size={16} style={{flex:1}}>{month(start)} – {month(end)}</Txt><Pressable accessibilityRole="button" accessibilityLabel="Previous week" onPress={()=>setSelected(shiftDay(selected,-7))} style={{padding:10}}><Icon name="back" size={18}/></Pressable><Pressable accessibilityRole="button" onPress={()=>setSelected(null)} style={{paddingHorizontal:17,paddingVertical:10,borderRadius:99,backgroundColor:t.ink}}><Txt size={13} style={{color:'#fff'}}>Today</Txt></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Next week" onPress={()=>setSelected(shiftDay(selected,7))} style={{padding:10}}><Icon name="chevron" size={18}/></Pressable></Row>
  <Row style={{gap:4,justifyContent:'space-between'}}>{days.map(day=>{const chosen=selected===day;const hasPlan=workoutsOn(plan,day).length>0;const logged=s.sessions.some(x=>x.day_key===day&&!x.removed_at&&x.source!=='seed'&&x.source!=='simulated');return <Pressable key={day} accessibilityRole="button" accessibilityLabel={`${readableDay(day)}${hasPlan?', workout planned':''}${logged?', workout logged':''}`} accessibilityState={{selected:chosen}} onPress={()=>setSelected(day)} style={{flex:1,alignItems:'center',paddingVertical:10,gap:7,minHeight:86,borderRadius:18,borderWidth:1.5,borderColor:chosen?t.ink:day===today?t.line:'transparent',backgroundColor:chosen?t.card:'transparent'}}><Txt size={11} muted>{shortDay(day).slice(0,1)}</Txt><Txt size={17} bold={chosen}>{Number(day.slice(-2))}</Txt><View style={{height:6,width:6,borderRadius:3,backgroundColor:logged?t.ink:hasPlan?t.accent:'transparent'}}/></Pressable>;})}</Row>
  <Row><Txt size={11} muted style={{flex:1,letterSpacing:1.5}}>{selected===today?'TODAY':readableDay(selected).toUpperCase()}</Txt>{loaded&&<Pressable accessibilityRole="button" accessibilityLabel="Plan another workout" onPress={add} style={{padding:10}}><Icon name="plus" size={18}/></Pressable>}</Row>
  {notice!==''&&<Txt size={12} muted>{notice}</Txt>}
  {!loaded?<Txt muted>Loading your week…</Txt>:workouts.length===0?<Pressable accessibilityRole="button" onPress={add} style={{borderRadius:26,paddingVertical:24,paddingHorizontal:22,backgroundColor:t.card,borderColor:t.line,borderWidth:1,borderStyle:'dashed',gap:10,alignItems:'center'}}><Txt serif size={25}>{completed.length?'You made time for yourself.':'Make a little time for you.'}</Txt><Txt muted size={14} style={{textAlign:'center'}}>{s.goals.length===1&&s.goals[0]?.activity_key==='gym'?'Choose what you’re training and when.':s.goals.length===1?`Pick a time for ${activity(s.goals[0]!.activity_key).short.toLowerCase()}.`:'Choose a workout and a time that suits you.'}</Txt><Txt bold size={12}>{completed.length?'Plan your next session':'Set a time & reminder'} →</Txt></Pressable>:workouts.map(workout=>{
   const done=completed.some(x=>x.activity_key===workout.activity_key);const title=workout.focus||activity(workout.activity_key).label;return <Pressable key={workout.id} accessibilityRole="button" accessibilityLabel={`Edit ${title} for ${readableDay(selected)}`} onPress={()=>setEditing(workout)}><Card style={{padding:20,borderWidth:0,gap:12}}><Row style={{gap:16}}><ActivityArt activityKey={workout.activity_key} size={66}/><View style={{flex:1,gap:5}}><Txt serif size={25}>{title}</Txt><Txt muted size={12}>{done?'Logged. You showed up.':workout.time?`${formatPlanTime(workout.time)}${workout.reminder?' · reminder 1 hour before':''}`:`${fullDays[weekdayOf(selected)]} is your ${activity(workout.activity_key).short.toLowerCase()} day.`}</Txt></View><Icon name={done?'check':'chevron'} size={18}/></Row>{!done&&<Txt size={12} bold>{workout.time?'Your time is set. Tap to make a change.':workout.activity_key==='gym'?'What are you training? Set your focus & time.':'Give yourself a time to show up.'}</Txt>}</Card></Pressable>;
  })}
  {removed.map(item=><Row key={item.rule_id}><Txt muted size={12} style={{flex:1}}>{activity(item.activity_key).label} skipped for this day.</Txt><Pressable accessibilityRole="button" onPress={()=>void persist(restorePlannedWorkout(plan,selected,item.rule_id)).catch(e=>setNotice(safeMessage(e)))} style={{padding:12}}><Txt bold size={12}>Undo</Txt></Pressable></Row>)}
  {editing&&<PlanEditor workout={editing} snapshot={s} onClose={()=>setEditing(null)} onSave={async(workout,repeat)=>{await persist(savePlannedWorkout(plan,workout,repeat));setNotice(repeat?'Your weekly time is set. You can change any single day.':'Saved for this day. Your usual week stays the same.');setEditing(null);}} onRemove={async repeat=>{await persist(removePlannedWorkout(plan,editing,repeat));setNotice(repeat?'Weekly plan removed.':'Skipped for this day. Your usual week stays the same.');setEditing(null);}}/>}
 </View>;
}

function PlanEditor({workout,snapshot:s,onClose,onSave,onRemove}:{workout:PlannedWorkout;snapshot:Snapshot;onClose:()=>void;onSave:(workout:PlannedWorkout,repeat:boolean)=>Promise<void>;onRemove:(repeat:boolean)=>Promise<void>}){
 const t=useTheme();const [value,setValue]=useState({...workout,time:workout.time??periodTime(workout.period)});const [repeat,setRepeat]=useState(workout.recurring&&!workout.time&&!workout.changed);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const keys=[...new Set<ActivityKey>([...s.goals.map(g=>g.activity_key),...activities.map(a=>a.key),value.activity_key])];
 const run=(fn:()=>Promise<void>)=>{setBusy(true);setError('');void fn().catch(e=>setError(safeMessage(e))).finally(()=>setBusy(false));};
 return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={{flex:1,justifyContent:'flex-end',backgroundColor:'#00000035'}}><Pressable accessibilityLabel="Close workout plan" onPress={onClose} style={{minHeight:30,flex:1}}/><SafeAreaView edges={['bottom']} style={{backgroundColor:t.paper,borderTopLeftRadius:30,borderTopRightRadius:30,maxHeight:'93%'}}><View style={{alignSelf:'center',width:42,height:4,backgroundColor:t.line,borderRadius:2,marginTop:12}}/><Row style={{paddingHorizontal:20,paddingVertical:15}}><Txt serif size={27} style={{flex:1}}>Make time for you.</Txt><Pressable accessibilityLabel="Close workout plan" onPress={onClose} style={{padding:12}}><Icon name="x"/></Pressable></Row>
  <ScrollView keyboardShouldPersistTaps="handled" automaticallyAdjustKeyboardInsets contentContainerStyle={{padding:20,paddingTop:0,gap:20}}><Txt muted size={13}>{readableDay(workout.day)}</Txt>
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:9}}>{keys.map(key=><Pressable key={key} accessibilityRole="button" accessibilityLabel={activity(key).label} accessibilityState={{selected:value.activity_key===key}} onPress={()=>setValue(v=>({...v,activity_key:key,focus:''}))} style={{width:98,padding:11,borderRadius:24,borderWidth:1.5,borderColor:value.activity_key===key?t.ink:t.line,alignItems:'center',gap:8,backgroundColor:t.card}}><ActivityArt activityKey={key} size={55}/><Txt size={11} style={{textAlign:'center'}}>{activity(key).short}</Txt></Pressable>)}</ScrollView>
   <CustomActivity onAdd={activity_key=>setValue(v=>({...v,activity_key,focus:''}))}/>
   {value.activity_key==='gym'&&<View style={{gap:10}}><Input label="What are you training? (optional)" value={value.focus} onChange={focus=>setValue(v=>({...v,focus:focus.slice(0,60)}))} placeholder="For example, upper body"/><Row style={{flexWrap:'wrap',gap:7}}>{['Push','Pull','Legs','Full body'].map(focus=><Chip key={focus} title={focus} selected={value.focus===focus} onPress={()=>setValue(v=>({...v,focus:v.focus===focus?'':focus}))}/>)}</Row></View>}
   <View style={{gap:9}}><Txt bold size={12}>Your time</Txt><PlanTimePicker value={value.time} onChange={time=>setValue(v=>({...v,time}))}/></View>
   <View style={{gap:10}}><Txt bold size={12}>Apply to</Txt><Row><View style={{flex:1}}><Chip title="Only this day" selected={!repeat} onPress={()=>setRepeat(false)}/></View><View style={{flex:1}}><Chip title={`Every ${fullDays[weekdayOf(workout.day)]}`} selected={repeat} onPress={()=>setRepeat(true)}/></View></Row></View>
   <Card style={{gap:9}}><Row><Icon name="bell"/><View style={{flex:1}}><Txt bold size={14}>A little encouragement</Txt><Txt muted size={12}>Remind me 1 hour before</Txt></View><Switch accessibilityLabel="Remind me one hour before" value={value.reminder} onValueChange={reminder=>setValue(v=>({...v,reminder}))} thumbColor="#fff" trackColor={{false:t.line,true:t.ink}}/></Row>{s.profile.notification_preferences.usual===false&&<Txt muted size={11}>Usual-day reminders are off in notification settings. Turn them on there to receive this reminder.</Txt>}</Card>
   <Txt muted size={11}>Plans and reminders stay on this phone. Your visit still logs automatically when tracking is on.</Txt>
   {!!error&&<Txt size={12}>{error}</Txt>}
   <Button dark disabled={busy} title={busy?'Saving…':repeat?'Save weekly plan':'Save for this day'} onPress={()=>run(async()=>{const denied=value.reminder&&s.profile.notification_preferences.usual!==false&&!await enableNotifications();await onSave(value,repeat);if(denied)Alert.alert('Plan saved without a phone notification','You can allow notifications for ClassStreak in iPhone Settings.');})}/>
   {(workout.recurring||workout.changed)&&<Button secondary disabled={busy} title={repeat?'Remove weekly plan':'Skip this day'} onPress={()=>run(()=>onRemove(repeat))}/>}
  </ScrollView>
 </SafeAreaView></View></Modal>;
}
