import {build} from 'esbuild';
import {mkdir,writeFile,copyFile} from 'node:fs/promises';
import {fresh,actor,rpc,A} from '../tests/database-harness.mjs';
await mkdir('build/gallery',{recursive:true});
const db=await fresh();await actor(db,A);await rpc(db,'cs_bootstrap',[{first_name:'Saad',last_name:'Shabbir',selected:['reformer','yoga','gym'],goals:{reformer:2,yoga:1,gym:0},days:[1,3,5],time:'evening',tz:'America/Los_Angeles'}]);
await rpc(db,'cs_settings',['place',{name:'Club Pilates Summerlin',activity_key:'reformer',lat:0,lng:0,radius_m:100}]);
await writeFile('build/gallery/fixture.json',JSON.stringify(await rpc(db,'cs_seed_demo',[false,[]])));await db.close();
const fonts=['fraunces/600SemiBold/Fraunces_600SemiBold','manrope/400Regular/Manrope_400Regular','manrope/700Bold/Manrope_700Bold','manrope/800ExtraBold/Manrope_800ExtraBold'];
let css='';for(const font of fonts){const name=font.split('/').at(-1);await copyFile('node_modules/@expo-google-fonts/'+font+'.ttf','build/gallery/'+name+'.ttf');css+=`@font-face{font-family:${name};src:url(${name}.ttf)}`;}
await writeFile('build/gallery/index.html',`<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>ClassStreak · UI review</title><style>${css}*{box-sizing:border-box}html,body,#root{margin:0;height:100%;font-family:Manrope_400Regular}#root{display:flex;flex-direction:column;background:#FBF0F2}nav{height:36px;flex-shrink:0;background:#1d171b;color:white;display:flex;align-items:center;gap:6px;padding:5px;font-size:9px}select{max-width:105px;font-size:11px}main{flex:1;min-height:0;display:flex;flex-direction:column}</style><div id="root"></div><script src="bundle.js"></script></html>`);
await build({entryPoints:['scripts/gallery.jsx'],outfile:'build/gallery/bundle.js',bundle:true,loader:{'.js':'jsx'},platform:'browser',minify:false,define:{'process.env.NODE_ENV':'"development"','process.env.EXPO_PUBLIC_GOOGLE_PLACES_KEY':'"preview"'},alias:{'react-native':'react-native-web'},resolveExtensions:['.web.tsx','.web.ts','.web.js','.tsx','.ts','.jsx','.js','.json'],plugins:[{name:'preview-only-native-adapters',setup(b){
 b.onResolve({filter:/^(expo-location|react-native-share|react-native-view-shot|expo-camera|expo-image-picker|expo-blur)$|^\.\/api$|^\.\/photos$/},args=>({path:args.path,namespace:'preview'}));
 b.onLoad({filter:/.*/,namespace:'preview'},args=>({loader:'jsx',resolveDir:process.cwd(),contents:`import React from 'react';import {View} from 'react-native-web';export const call=async()=>null;export const readPhoto=async()=>null;export const queuePhoto=async()=>false;export const saveToPhotos=async()=>{};export const sharePhoto=async()=>{};export const captureRef=async()=>'';export const CameraView=React.forwardRef((p,r)=><View ref={r} style={[p.style,{backgroundColor:'#604656'}]}/>);export const BlurView=View;export const useCameraPermissions=()=>[{granted:true},async()=>({granted:true})];export const launchImageLibraryAsync=async()=>({canceled:true});export const Accuracy={Balanced:3};export const getForegroundPermissionsAsync=async()=>({granted:false});export const requestForegroundPermissionsAsync=async()=>({granted:false});export const requestBackgroundPermissionsAsync=async()=>({granted:false});export const getCurrentPositionAsync=async()=>({coords:{latitude:0,longitude:0}});export default {open:async()=>{}};`}));
 }}]});
console.log('Gallery uses real screen components and disposable database fixtures; native actions are preview-only.');
